<?php
namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CiudadesSeeder extends Seeder
{
    public function run(): void
    {
        $ciudades = [
            ['nombre' => '	MEDELLIN	', 'codigo_dian' => 5001, 'departamento_id' => 1],
            ['nombre' => '	ABEJORRAL	', 'codigo_dian' => 5002, 'departamento_id' => 1],
            ['nombre' => '	ABRIAQUI	', 'codigo_dian' => 5004, 'departamento_id' => 1],
            ['nombre' => '	ALEJANDRIA	', 'codigo_dian' => 5021, 'departamento_id' => 1],
            ['nombre' => '	AMAGA	', 'codigo_dian' => 5030, 'departamento_id' => 1],
            ['nombre' => '	AMALFI	', 'codigo_dian' => 5031, 'departamento_id' => 1],
            ['nombre' => '	ANDES	', 'codigo_dian' => 5034, 'departamento_id' => 1],
            ['nombre' => '	ANGELOPOLIS	', 'codigo_dian' => 5036, 'departamento_id' => 1],
            ['nombre' => '	ANGOSTURA	', 'codigo_dian' => 5038, 'departamento_id' => 1],
            ['nombre' => '	ANORI	', 'codigo_dian' => 5040, 'departamento_id' => 1],
            ['nombre' => '	ANTIOQUIA	', 'codigo_dian' => 5042, 'departamento_id' => 1],
            ['nombre' => '	ANZA	', 'codigo_dian' => 5044, 'departamento_id' => 1],
            ['nombre' => '	APARTADO	', 'codigo_dian' => 5045, 'departamento_id' => 1],
            ['nombre' => '	ARBOLETES	', 'codigo_dian' => 5051, 'departamento_id' => 1],
            ['nombre' => '	ARGELIA	', 'codigo_dian' => 5055, 'departamento_id' => 1],
            ['nombre' => '	ARMENIA	', 'codigo_dian' => 5059, 'departamento_id' => 1],
            ['nombre' => '	BARBOSA	', 'codigo_dian' => 5079, 'departamento_id' => 1],
            ['nombre' => '	BELMIRA	', 'codigo_dian' => 5086, 'departamento_id' => 1],
            ['nombre' => '	BELLO	', 'codigo_dian' => 5088, 'departamento_id' => 1],
            ['nombre' => '	BETANIA	', 'codigo_dian' => 5091, 'departamento_id' => 1],
            ['nombre' => '	BETULIA	', 'codigo_dian' => 5093, 'departamento_id' => 1],
            ['nombre' => '	CIUDAD BOLIVAR	', 'codigo_dian' => 5101, 'departamento_id' => 1],
            ['nombre' => '	BRICEÑO	', 'codigo_dian' => 5107, 'departamento_id' => 1],
            ['nombre' => '	BURITICA	', 'codigo_dian' => 5113, 'departamento_id' => 1],
            ['nombre' => '	CACERES	', 'codigo_dian' => 5120, 'departamento_id' => 1],
            ['nombre' => '	CAICEDO	', 'codigo_dian' => 5125, 'departamento_id' => 1],
            ['nombre' => '	CALDAS	', 'codigo_dian' => 5129, 'departamento_id' => 1],
            ['nombre' => '	CAMPAMENTO	', 'codigo_dian' => 5134, 'departamento_id' => 1],
            ['nombre' => '	CAÑASGORDAS	', 'codigo_dian' => 5138, 'departamento_id' => 1],
            ['nombre' => '	CARACOLI	', 'codigo_dian' => 5142, 'departamento_id' => 1],
            ['nombre' => '	CARAMANTA	', 'codigo_dian' => 5145, 'departamento_id' => 1],
            ['nombre' => '	CAREPA	', 'codigo_dian' => 5147, 'departamento_id' => 1],
            ['nombre' => '	CARMEN DE VIBORAL	', 'codigo_dian' => 5148, 'departamento_id' => 1],
            ['nombre' => '	CAROLINA	', 'codigo_dian' => 5150, 'departamento_id' => 1],
            ['nombre' => '	CAUCASIA	', 'codigo_dian' => 5154, 'departamento_id' => 1],
            ['nombre' => '	CHIGORODO	', 'codigo_dian' => 5172, 'departamento_id' => 1],
            ['nombre' => '	CISNEROS	', 'codigo_dian' => 5190, 'departamento_id' => 1],
            ['nombre' => '	COCORNA	', 'codigo_dian' => 5197, 'departamento_id' => 1],
            ['nombre' => '	CONCEPCION	', 'codigo_dian' => 5206, 'departamento_id' => 1],
            ['nombre' => '	CONCORDIA	', 'codigo_dian' => 5209, 'departamento_id' => 1],
            ['nombre' => '	COPACABANA	', 'codigo_dian' => 5212, 'departamento_id' => 1],
            ['nombre' => '	DABEIBA	', 'codigo_dian' => 5234, 'departamento_id' => 1],
            ['nombre' => '	DON MATIAS	', 'codigo_dian' => 5237, 'departamento_id' => 1],
            ['nombre' => '	EBEJICO	', 'codigo_dian' => 5240, 'departamento_id' => 1],
            ['nombre' => '	EL BAGRE	', 'codigo_dian' => 5250, 'departamento_id' => 1],
            ['nombre' => '	ENTRERRIOS	', 'codigo_dian' => 5264, 'departamento_id' => 1],
            ['nombre' => '	ENVIGADO	', 'codigo_dian' => 5266, 'departamento_id' => 1],
            ['nombre' => '	FREDONIA	', 'codigo_dian' => 5282, 'departamento_id' => 1],
            ['nombre' => '	FRONTINO	', 'codigo_dian' => 5284, 'departamento_id' => 1],
            ['nombre' => '	GIRALDO	', 'codigo_dian' => 5306, 'departamento_id' => 1],
            ['nombre' => '	GIRARDOTA	', 'codigo_dian' => 5308, 'departamento_id' => 1],
            ['nombre' => '	GOMEZ PLATA	', 'codigo_dian' => 5310, 'departamento_id' => 1],
            ['nombre' => '	GRANADA	', 'codigo_dian' => 5313, 'departamento_id' => 1],
            ['nombre' => '	GUADALUPE	', 'codigo_dian' => 5315, 'departamento_id' => 1],
            ['nombre' => '	GUARNE	', 'codigo_dian' => 5318, 'departamento_id' => 1],
            ['nombre' => '	GUATAPE	', 'codigo_dian' => 5321, 'departamento_id' => 1],
            ['nombre' => '	HELICONIA	', 'codigo_dian' => 5347, 'departamento_id' => 1],
            ['nombre' => '	HISPANIA	', 'codigo_dian' => 5353, 'departamento_id' => 1],
            ['nombre' => '	ITAGUI	', 'codigo_dian' => 5360, 'departamento_id' => 1],
            ['nombre' => '	ITUANGO	', 'codigo_dian' => 5361, 'departamento_id' => 1],
            ['nombre' => '	JARDIN	', 'codigo_dian' => 5364, 'departamento_id' => 1],
            ['nombre' => '	JERICO	', 'codigo_dian' => 5368, 'departamento_id' => 1],
            ['nombre' => '	LA CEJA	', 'codigo_dian' => 5376, 'departamento_id' => 1],
            ['nombre' => '	LA ESTRELLA	', 'codigo_dian' => 5380, 'departamento_id' => 1],
            ['nombre' => '	LA PINTADA	', 'codigo_dian' => 5390, 'departamento_id' => 1],
            ['nombre' => '	LA UNION	', 'codigo_dian' => 5400, 'departamento_id' => 1],
            ['nombre' => '	LIBORINA	', 'codigo_dian' => 5411, 'departamento_id' => 1],
            ['nombre' => '	MACEO	', 'codigo_dian' => 5425, 'departamento_id' => 1],
            ['nombre' => '	MARINILLA	', 'codigo_dian' => 5440, 'departamento_id' => 1],
            ['nombre' => '	MONTEBELLO	', 'codigo_dian' => 5467, 'departamento_id' => 1],
            ['nombre' => '	MURINDO	', 'codigo_dian' => 5475, 'departamento_id' => 1],
            ['nombre' => '	MUTATA	', 'codigo_dian' => 5480, 'departamento_id' => 1],
            ['nombre' => '	NARIÑO	', 'codigo_dian' => 5483, 'departamento_id' => 1],
            ['nombre' => '	NECOCLI	', 'codigo_dian' => 5490, 'departamento_id' => 1],
            ['nombre' => '	NECHI	', 'codigo_dian' => 5495, 'departamento_id' => 1],
            ['nombre' => '	OLAYA	', 'codigo_dian' => 5501, 'departamento_id' => 1],
            ['nombre' => '	PEÑOL	', 'codigo_dian' => 5541, 'departamento_id' => 1],
            ['nombre' => '	PEQUE	', 'codigo_dian' => 5543, 'departamento_id' => 1],
            ['nombre' => '	PUEBLORRICO	', 'codigo_dian' => 5576, 'departamento_id' => 1],
            ['nombre' => '	PUERTO BERRIO	', 'codigo_dian' => 5579, 'departamento_id' => 1],
            ['nombre' => '	PUERTO NARE	', 'codigo_dian' => 5585, 'departamento_id' => 1],
            ['nombre' => '	PUERTO TRIUNFO	', 'codigo_dian' => 5591, 'departamento_id' => 1],
            ['nombre' => '	REMEDIOS	', 'codigo_dian' => 5604, 'departamento_id' => 1],
            ['nombre' => '	RETIRO	', 'codigo_dian' => 5607, 'departamento_id' => 1],
            ['nombre' => '	RIONEGRO	', 'codigo_dian' => 5615, 'departamento_id' => 1],
            ['nombre' => '	SABANALARGA	', 'codigo_dian' => 5628, 'departamento_id' => 1],
            ['nombre' => '	SABANETA	', 'codigo_dian' => 5631, 'departamento_id' => 1],
            ['nombre' => '	SALGAR	', 'codigo_dian' => 5642, 'departamento_id' => 1],
            ['nombre' => '	SAN ANDRES	', 'codigo_dian' => 5647, 'departamento_id' => 1],
            ['nombre' => '	SAN CARLOS	', 'codigo_dian' => 5649, 'departamento_id' => 1],
            ['nombre' => '	SAN FRANCISCO	', 'codigo_dian' => 5652, 'departamento_id' => 1],
            ['nombre' => '	SAN JERONIMO	', 'codigo_dian' => 5656, 'departamento_id' => 1],
            ['nombre' => '	SAN JOSE DE LA MONTAÑA	', 'codigo_dian' => 5658, 'departamento_id' => 1],
            ['nombre' => '	SAN JUAN DE URABA	', 'codigo_dian' => 5659, 'departamento_id' => 1],
            ['nombre' => '	SAN LUIS	', 'codigo_dian' => 5660, 'departamento_id' => 1],
            ['nombre' => '	SAN PEDRO	', 'codigo_dian' => 5664, 'departamento_id' => 1],
            ['nombre' => '	SAN PEDRO DE URABA	', 'codigo_dian' => 5665, 'departamento_id' => 1],
            ['nombre' => '	SAN RAFAEL	', 'codigo_dian' => 5667, 'departamento_id' => 1],
            ['nombre' => '	SAN ROQUE	', 'codigo_dian' => 5670, 'departamento_id' => 1],
            ['nombre' => '	SAN VICENTE	', 'codigo_dian' => 5674, 'departamento_id' => 1],
            ['nombre' => '	SANTA BARBARA	', 'codigo_dian' => 5679, 'departamento_id' => 1],
            ['nombre' => '	SANTA ROSA DE OSOS	', 'codigo_dian' => 5686, 'departamento_id' => 1],
            ['nombre' => '	SANTO DOMINGO	', 'codigo_dian' => 5690, 'departamento_id' => 1],
            ['nombre' => '	SANTUARIO	', 'codigo_dian' => 5697, 'departamento_id' => 1],
            ['nombre' => '	SEGOVIA	', 'codigo_dian' => 5736, 'departamento_id' => 1],
            ['nombre' => '	SONSON	', 'codigo_dian' => 5756, 'departamento_id' => 1],
            ['nombre' => '	SOPETRAN	', 'codigo_dian' => 5761, 'departamento_id' => 1],
            ['nombre' => '	TAZON	', 'codigo_dian' => 5789, 'departamento_id' => 1],
            ['nombre' => '	TARAZA	', 'codigo_dian' => 5790, 'departamento_id' => 1],
            ['nombre' => '	TARSO	', 'codigo_dian' => 5792, 'departamento_id' => 1],
            ['nombre' => '	TITIRIBI	', 'codigo_dian' => 5809, 'departamento_id' => 1],
            ['nombre' => '	TOLEDO	', 'codigo_dian' => 5819, 'departamento_id' => 1],
            ['nombre' => '	TURBO	', 'codigo_dian' => 5837, 'departamento_id' => 1],
            ['nombre' => '	URAMITA	', 'codigo_dian' => 5842, 'departamento_id' => 1],
            ['nombre' => '	URRAO	', 'codigo_dian' => 5847, 'departamento_id' => 1],
            ['nombre' => '	VALDIVIA	', 'codigo_dian' => 5854, 'departamento_id' => 1],
            ['nombre' => '	VALPARAISO	', 'codigo_dian' => 5856, 'departamento_id' => 1],
            ['nombre' => '	VEGACHI	', 'codigo_dian' => 5858, 'departamento_id' => 1],
            ['nombre' => '	VENECIA	', 'codigo_dian' => 5861, 'departamento_id' => 1],
            ['nombre' => '	VIGIA DEL FUERTE	', 'codigo_dian' => 5873, 'departamento_id' => 1],
            ['nombre' => '	YALI	', 'codigo_dian' => 5885, 'departamento_id' => 1],
            ['nombre' => '	YARUMAL	', 'codigo_dian' => 5887, 'departamento_id' => 1],
            ['nombre' => '	YOLOMBO	', 'codigo_dian' => 5890, 'departamento_id' => 1],
            ['nombre' => '	YONDO	', 'codigo_dian' => 5893, 'departamento_id' => 1],
            ['nombre' => '	ZARAGOZA	', 'codigo_dian' => 5895, 'departamento_id' => 1],
            ['nombre' => '	BARRANQUILLA	', 'codigo_dian' => 8001, 'departamento_id' => 2],
            ['nombre' => '	BARANOA	', 'codigo_dian' => 8078, 'departamento_id' => 2],
            ['nombre' => '	CAMPO DE LA CRUZ	', 'codigo_dian' => 8137, 'departamento_id' => 2],
            ['nombre' => '	CANDELARIA	', 'codigo_dian' => 8141, 'departamento_id' => 2],
            ['nombre' => '	GALAPA	', 'codigo_dian' => 8296, 'departamento_id' => 2],
            ['nombre' => '	JUAN DE ACOSTA	', 'codigo_dian' => 8372, 'departamento_id' => 2],
            ['nombre' => '	LURUACO	', 'codigo_dian' => 8421, 'departamento_id' => 2],
            ['nombre' => '	MALAMBO	', 'codigo_dian' => 8433, 'departamento_id' => 2],
            ['nombre' => '	MANATI	', 'codigo_dian' => 8436, 'departamento_id' => 2],
            ['nombre' => '	PALMAR DE VARELA	', 'codigo_dian' => 8520, 'departamento_id' => 2],
            ['nombre' => '	PIOJO	', 'codigo_dian' => 8549, 'departamento_id' => 2],
            ['nombre' => '	POLO NUEVO	', 'codigo_dian' => 8558, 'departamento_id' => 2],
            ['nombre' => '	PONEDERA	', 'codigo_dian' => 8560, 'departamento_id' => 2],
            ['nombre' => '	PUERTO COLOMBIA	', 'codigo_dian' => 8573, 'departamento_id' => 2],
            ['nombre' => '	REPELON	', 'codigo_dian' => 8606, 'departamento_id' => 2],
            ['nombre' => '	SABANAGRANDE	', 'codigo_dian' => 8634, 'departamento_id' => 2],
            ['nombre' => '	SABANALARGA	', 'codigo_dian' => 8638, 'departamento_id' => 2],
            ['nombre' => '	SANTA LUCIA	', 'codigo_dian' => 8675, 'departamento_id' => 2],
            ['nombre' => '	SANTO TOMAS	', 'codigo_dian' => 8685, 'departamento_id' => 2],
            ['nombre' => '	SOLEDAD	', 'codigo_dian' => 8758, 'departamento_id' => 2],
            ['nombre' => '	SUAN	', 'codigo_dian' => 8770, 'departamento_id' => 2],
            ['nombre' => '	TUBARA	', 'codigo_dian' => 8832, 'departamento_id' => 2],
            ['nombre' => '	USIACURI	', 'codigo_dian' => 8849, 'departamento_id' => 2],
            ['nombre' => '	BOGOTA	', 'codigo_dian' => 11001, 'departamento_id' => 3],
            ['nombre' => '	CARTAGENA	', 'codigo_dian' => 13001, 'departamento_id' => 4],
            ['nombre' => '	ACHI	', 'codigo_dian' => 13006, 'departamento_id' => 4],
            ['nombre' => '	ALTOS DEL ROSARIO	', 'codigo_dian' => 13030, 'departamento_id' => 4],
            ['nombre' => '	ARENAL	', 'codigo_dian' => 13042, 'departamento_id' => 4],
            ['nombre' => '	ARJONA	', 'codigo_dian' => 13052, 'departamento_id' => 4],
            ['nombre' => '	ARROYOHONDO	', 'codigo_dian' => 13062, 'departamento_id' => 4],
            ['nombre' => '	BARRANCO DE LOBA	', 'codigo_dian' => 13074, 'departamento_id' => 4],
            ['nombre' => '	CALAMAR	', 'codigo_dian' => 13140, 'departamento_id' => 4],
            ['nombre' => '	CANTAGALLO	', 'codigo_dian' => 13160, 'departamento_id' => 4],
            ['nombre' => '	CICUCO	', 'codigo_dian' => 13188, 'departamento_id' => 4],
            ['nombre' => '	CORDOBA	', 'codigo_dian' => 13212, 'departamento_id' => 4],
            ['nombre' => '	CLEMENCIA	', 'codigo_dian' => 13222, 'departamento_id' => 4],
            ['nombre' => '	EL CARMEN DE BOLIVAR	', 'codigo_dian' => 13244, 'departamento_id' => 4],
            ['nombre' => '	EL GUAMO	', 'codigo_dian' => 13248, 'departamento_id' => 4],
            ['nombre' => '	EL PEÑON	', 'codigo_dian' => 13268, 'departamento_id' => 4],
            ['nombre' => '	HATILLO DE LOBA	', 'codigo_dian' => 13300, 'departamento_id' => 4],
            ['nombre' => '	MAGANGUE	', 'codigo_dian' => 13430, 'departamento_id' => 4],
            ['nombre' => '	MAHATES	', 'codigo_dian' => 13433, 'departamento_id' => 4],
            ['nombre' => '	MARGARITA	', 'codigo_dian' => 13440, 'departamento_id' => 4],
            ['nombre' => '	MARIA LA BAJA	', 'codigo_dian' => 13442, 'departamento_id' => 4],
            ['nombre' => '	MONTECRISTO	', 'codigo_dian' => 13458, 'departamento_id' => 4],
            ['nombre' => '	MOMPOS	', 'codigo_dian' => 13468, 'departamento_id' => 4],
            ['nombre' => '	MORALES	', 'codigo_dian' => 13473, 'departamento_id' => 4],
            ['nombre' => '	PINILLOS	', 'codigo_dian' => 13549, 'departamento_id' => 4],
            ['nombre' => '	REGIDOR	', 'codigo_dian' => 13580, 'departamento_id' => 4],
            ['nombre' => '	RIO VIEJO	', 'codigo_dian' => 13600, 'departamento_id' => 4],
            ['nombre' => '	SAN CRISTOBAL	', 'codigo_dian' => 13620, 'departamento_id' => 4],
            ['nombre' => '	SAN ESTANISLAO	', 'codigo_dian' => 13647, 'departamento_id' => 4],
            ['nombre' => '	SAN FERNANDO	', 'codigo_dian' => 13650, 'departamento_id' => 4],
            ['nombre' => '	SAN JACINTO	', 'codigo_dian' => 13654, 'departamento_id' => 4],
            ['nombre' => '	SAN JACINTO DEL CAUCA	', 'codigo_dian' => 13655, 'departamento_id' => 4],
            ['nombre' => '	SAN JUAN NEPOMUCENO	', 'codigo_dian' => 13657, 'departamento_id' => 4],
            ['nombre' => '	SAN MARTIN DE LOBA	', 'codigo_dian' => 13667, 'departamento_id' => 4],
            ['nombre' => '	SAN PABLO	', 'codigo_dian' => 13670, 'departamento_id' => 4],
            ['nombre' => '	SANTA CATALINA	', 'codigo_dian' => 13673, 'departamento_id' => 4],
            ['nombre' => '	SANTA ROSA	', 'codigo_dian' => 13683, 'departamento_id' => 4],
            ['nombre' => '	SANTA ROSA DEL SUR	', 'codigo_dian' => 13688, 'departamento_id' => 4],
            ['nombre' => '	SIMITI	', 'codigo_dian' => 13744, 'departamento_id' => 4],
            ['nombre' => '	SOPLAVIENTO	', 'codigo_dian' => 13760, 'departamento_id' => 4],
            ['nombre' => '	TALAIGUA NUEVO	', 'codigo_dian' => 13780, 'departamento_id' => 4],
            ['nombre' => '	TIQUISIO	', 'codigo_dian' => 13810, 'departamento_id' => 4],
            ['nombre' => '	TURBACO	', 'codigo_dian' => 13836, 'departamento_id' => 4],
            ['nombre' => '	TURBANA	', 'codigo_dian' => 13838, 'departamento_id' => 4],
            ['nombre' => '	VILLANUEVA	', 'codigo_dian' => 13873, 'departamento_id' => 4],
            ['nombre' => '	ZAMBRANO	', 'codigo_dian' => 13894, 'departamento_id' => 4],
            ['nombre' => '	TUNJA	', 'codigo_dian' => 15001, 'departamento_id' => 5],
            ['nombre' => '	ALMEIDA	', 'codigo_dian' => 15022, 'departamento_id' => 5],
            ['nombre' => '	AQUITANIA	', 'codigo_dian' => 15047, 'departamento_id' => 5],
            ['nombre' => '	ARCABUCO	', 'codigo_dian' => 15051, 'departamento_id' => 5],
            ['nombre' => '	BELEN	', 'codigo_dian' => 15087, 'departamento_id' => 5],
            ['nombre' => '	BERBEO	', 'codigo_dian' => 15090, 'departamento_id' => 5],
            ['nombre' => '	BETEITIVA	', 'codigo_dian' => 15092, 'departamento_id' => 5],
            ['nombre' => '	BOAVITA	', 'codigo_dian' => 15097, 'departamento_id' => 5],
            ['nombre' => '	BOYACA	', 'codigo_dian' => 15104, 'departamento_id' => 5],
            ['nombre' => '	BRICEÑO	', 'codigo_dian' => 15106, 'departamento_id' => 5],
            ['nombre' => '	BUENAVISTA	', 'codigo_dian' => 15109, 'departamento_id' => 5],
            ['nombre' => '	BUSBANZA	', 'codigo_dian' => 15114, 'departamento_id' => 5],
            ['nombre' => '	CALDAS	', 'codigo_dian' => 15131, 'departamento_id' => 5],
            ['nombre' => '	CAMPOHERMOSO	', 'codigo_dian' => 15135, 'departamento_id' => 5],
            ['nombre' => '	CERINZA	', 'codigo_dian' => 15162, 'departamento_id' => 5],
            ['nombre' => '	CHINAVITA	', 'codigo_dian' => 15172, 'departamento_id' => 5],
            ['nombre' => '	CHIQUINQUIRA	', 'codigo_dian' => 15176, 'departamento_id' => 5],
            ['nombre' => '	CHISCAS	', 'codigo_dian' => 15180, 'departamento_id' => 5],
            ['nombre' => '	CHITA	', 'codigo_dian' => 15183, 'departamento_id' => 5],
            ['nombre' => '	CHITARAQUE	', 'codigo_dian' => 15185, 'departamento_id' => 5],
            ['nombre' => '	CHIVATA	', 'codigo_dian' => 15187, 'departamento_id' => 5],
            ['nombre' => '	CIENEGA	', 'codigo_dian' => 15189, 'departamento_id' => 5],
            ['nombre' => '	COMBITA	', 'codigo_dian' => 15204, 'departamento_id' => 5],
            ['nombre' => '	COPER	', 'codigo_dian' => 15212, 'departamento_id' => 5],
            ['nombre' => '	CORRALES	', 'codigo_dian' => 15215, 'departamento_id' => 5],
            ['nombre' => '	COVARACHIA	', 'codigo_dian' => 15218, 'departamento_id' => 5],
            ['nombre' => '	CUBARA	', 'codigo_dian' => 15223, 'departamento_id' => 5],
            ['nombre' => '	CUCAITA	', 'codigo_dian' => 15224, 'departamento_id' => 5],
            ['nombre' => '	CUITIVA	', 'codigo_dian' => 15226, 'departamento_id' => 5],
            ['nombre' => '	CHIQUIZA	', 'codigo_dian' => 15232, 'departamento_id' => 5],
            ['nombre' => '	CHIVOR	', 'codigo_dian' => 15236, 'departamento_id' => 5],
            ['nombre' => '	DUITAMA	', 'codigo_dian' => 15238, 'departamento_id' => 5],
            ['nombre' => '	EL COCUY	', 'codigo_dian' => 15244, 'departamento_id' => 5],
            ['nombre' => '	EL ESPINO	', 'codigo_dian' => 15248, 'departamento_id' => 5],
            ['nombre' => '	FIRAVITOBA	', 'codigo_dian' => 15272, 'departamento_id' => 5],
            ['nombre' => '	FLORESTA	', 'codigo_dian' => 15276, 'departamento_id' => 5],
            ['nombre' => '	GACHANTIVA	', 'codigo_dian' => 15293, 'departamento_id' => 5],
            ['nombre' => '	GAMEZA	', 'codigo_dian' => 15296, 'departamento_id' => 5],
            ['nombre' => '	GARAGOA	', 'codigo_dian' => 15299, 'departamento_id' => 5],
            ['nombre' => '	GUACAMAYAS	', 'codigo_dian' => 15317, 'departamento_id' => 5],
            ['nombre' => '	GUATEQUE	', 'codigo_dian' => 15322, 'departamento_id' => 5],
            ['nombre' => '	GUAYATA	', 'codigo_dian' => 15325, 'departamento_id' => 5],
            ['nombre' => '	GUICAN	', 'codigo_dian' => 15332, 'departamento_id' => 5],
            ['nombre' => '	IZA	', 'codigo_dian' => 15362, 'departamento_id' => 5],
            ['nombre' => '	JENESANO	', 'codigo_dian' => 15367, 'departamento_id' => 5],
            ['nombre' => '	JERICO	', 'codigo_dian' => 15368, 'departamento_id' => 5],
            ['nombre' => '	LABRANZAGRANDE	', 'codigo_dian' => 15377, 'departamento_id' => 5],
            ['nombre' => '	LA CAPILLA	', 'codigo_dian' => 15380, 'departamento_id' => 5],
            ['nombre' => '	LA VICTORIA	', 'codigo_dian' => 15401, 'departamento_id' => 5],
            ['nombre' => '	LA UVITA	', 'codigo_dian' => 15403, 'departamento_id' => 5],
            ['nombre' => '	LEIVA	', 'codigo_dian' => 15407, 'departamento_id' => 5],
            ['nombre' => '	MACANAL	', 'codigo_dian' => 15425, 'departamento_id' => 5],
            ['nombre' => '	MARIPI	', 'codigo_dian' => 15442, 'departamento_id' => 5],
            ['nombre' => '	MIRAFLORES	', 'codigo_dian' => 15455, 'departamento_id' => 5],
            ['nombre' => '	MONGUA	', 'codigo_dian' => 15464, 'departamento_id' => 5],
            ['nombre' => '	MONGUI	', 'codigo_dian' => 15466, 'departamento_id' => 5],
            ['nombre' => '	MONIQUIRA	', 'codigo_dian' => 15469, 'departamento_id' => 5],
            ['nombre' => '	MOTAVITA	', 'codigo_dian' => 15476, 'departamento_id' => 5],
            ['nombre' => '	MUZO	', 'codigo_dian' => 15480, 'departamento_id' => 5],
            ['nombre' => '	NOBSA	', 'codigo_dian' => 15491, 'departamento_id' => 5],
            ['nombre' => '	NUEVO COLON	', 'codigo_dian' => 15494, 'departamento_id' => 5],
            ['nombre' => '	OICATA	', 'codigo_dian' => 15500, 'departamento_id' => 5],
            ['nombre' => '	OTANCHE	', 'codigo_dian' => 15507, 'departamento_id' => 5],
            ['nombre' => '	PACHAVITA	', 'codigo_dian' => 15511, 'departamento_id' => 5],
            ['nombre' => '	PAEZ	', 'codigo_dian' => 15514, 'departamento_id' => 5],
            ['nombre' => '	PAIPA	', 'codigo_dian' => 15516, 'departamento_id' => 5],
            ['nombre' => '	PAJARITO	', 'codigo_dian' => 15518, 'departamento_id' => 5],
            ['nombre' => '	PANQUEBA	', 'codigo_dian' => 15522, 'departamento_id' => 5],
            ['nombre' => '	PAUNA	', 'codigo_dian' => 15531, 'departamento_id' => 5],
            ['nombre' => '	PAYA	', 'codigo_dian' => 15533, 'departamento_id' => 5],
            ['nombre' => '	PAZ DEL RIO	', 'codigo_dian' => 15537, 'departamento_id' => 5],
            ['nombre' => '	PESCA	', 'codigo_dian' => 15542, 'departamento_id' => 5],
            ['nombre' => '	PISBA	', 'codigo_dian' => 15550, 'departamento_id' => 5],
            ['nombre' => '	PUERTO BOYACA	', 'codigo_dian' => 15572, 'departamento_id' => 5],
            ['nombre' => '	QUIPAMA	', 'codigo_dian' => 15580, 'departamento_id' => 5],
            ['nombre' => '	RAMIRIQUI	', 'codigo_dian' => 15599, 'departamento_id' => 5],
            ['nombre' => '	RAQUIRA	', 'codigo_dian' => 15600, 'departamento_id' => 5],
            ['nombre' => '	RONDON	', 'codigo_dian' => 15621, 'departamento_id' => 5],
            ['nombre' => '	SABOYA	', 'codigo_dian' => 15632, 'departamento_id' => 5],
            ['nombre' => '	SACHICA	', 'codigo_dian' => 15638, 'departamento_id' => 5],
            ['nombre' => '	SAMACA	', 'codigo_dian' => 15646, 'departamento_id' => 5],
            ['nombre' => '	SAN EDUARDO	', 'codigo_dian' => 15660, 'departamento_id' => 5],
            ['nombre' => '	SAN JOSE DE PARE	', 'codigo_dian' => 15664, 'departamento_id' => 5],
            ['nombre' => '	SAN LUIS DE GACENO	', 'codigo_dian' => 15667, 'departamento_id' => 5],
            ['nombre' => '	SAN MATEO	', 'codigo_dian' => 15673, 'departamento_id' => 5],
            ['nombre' => '	SAN MIGUEL DE SEMA	', 'codigo_dian' => 15676, 'departamento_id' => 5],
            ['nombre' => '	AME	', 'codigo_dian' => 15681, 'departamento_id' => 5],
            ['nombre' => '	SANTANA	', 'codigo_dian' => 15686, 'departamento_id' => 5],
            ['nombre' => '	SANTA MARIA	', 'codigo_dian' => 15690, 'departamento_id' => 5],
            ['nombre' => '	SANTA ROSA DE VITERBO	', 'codigo_dian' => 15693, 'departamento_id' => 5],
            ['nombre' => '	SANTA SOFIA	', 'codigo_dian' => 15696, 'departamento_id' => 5],
            ['nombre' => '	SATIVANORTE	', 'codigo_dian' => 15720, 'departamento_id' => 5],
            ['nombre' => '	SATIVASUR	', 'codigo_dian' => 15723, 'departamento_id' => 5],
            ['nombre' => '	SIACHOQUE	', 'codigo_dian' => 15740, 'departamento_id' => 5],
            ['nombre' => '	SOATA	', 'codigo_dian' => 15753, 'departamento_id' => 5],
            ['nombre' => '	SOCOTA	', 'codigo_dian' => 15755, 'departamento_id' => 5],
            ['nombre' => '	SOCHA	', 'codigo_dian' => 15757, 'departamento_id' => 5],
            ['nombre' => '	SOGAMOSO	', 'codigo_dian' => 15759, 'departamento_id' => 5],
            ['nombre' => '	SOMONDOCO	', 'codigo_dian' => 15761, 'departamento_id' => 5],
            ['nombre' => '	SORA	', 'codigo_dian' => 15762, 'departamento_id' => 5],
            ['nombre' => '	SOTAQUIRA	', 'codigo_dian' => 15763, 'departamento_id' => 5],
            ['nombre' => '	SORACA	', 'codigo_dian' => 15764, 'departamento_id' => 5],
            ['nombre' => '	SUSACON	', 'codigo_dian' => 15774, 'departamento_id' => 5],
            ['nombre' => '	SUTAMARCHAN	', 'codigo_dian' => 15776, 'departamento_id' => 5],
            ['nombre' => '	SUTATENZA	', 'codigo_dian' => 15778, 'departamento_id' => 5],
            ['nombre' => '	TASCO	', 'codigo_dian' => 15790, 'departamento_id' => 5],
            ['nombre' => '	TENZA	', 'codigo_dian' => 15798, 'departamento_id' => 5],
            ['nombre' => '	TIBANA	', 'codigo_dian' => 15804, 'departamento_id' => 5],
            ['nombre' => '	TIBASOSA	', 'codigo_dian' => 15806, 'departamento_id' => 5],
            ['nombre' => '	TINJACA	', 'codigo_dian' => 15808, 'departamento_id' => 5],
            ['nombre' => '	TIPACOQUE	', 'codigo_dian' => 15810, 'departamento_id' => 5],
            ['nombre' => '	TOCA	', 'codigo_dian' => 15814, 'departamento_id' => 5],
            ['nombre' => '	TOGUI	', 'codigo_dian' => 15816, 'departamento_id' => 5],
            ['nombre' => '	TOPAGA	', 'codigo_dian' => 15820, 'departamento_id' => 5],
            ['nombre' => '	TOTA	', 'codigo_dian' => 15822, 'departamento_id' => 5],
            ['nombre' => '	TUNUNGUA	', 'codigo_dian' => 15832, 'departamento_id' => 5],
            ['nombre' => '	TURMEQUE	', 'codigo_dian' => 15835, 'departamento_id' => 5],
            ['nombre' => '	TUTA	', 'codigo_dian' => 15837, 'departamento_id' => 5],
            ['nombre' => '	TUTASA	', 'codigo_dian' => 15839, 'departamento_id' => 5],
            ['nombre' => '	UMBITA	', 'codigo_dian' => 15842, 'departamento_id' => 5],
            ['nombre' => '	VENTAQUEMADA	', 'codigo_dian' => 15861, 'departamento_id' => 5],
            ['nombre' => '	VIRACACHA	', 'codigo_dian' => 15879, 'departamento_id' => 5],
            ['nombre' => '	ZETAQUIRA	', 'codigo_dian' => 15897, 'departamento_id' => 5],
            ['nombre' => '	MANIZALES	', 'codigo_dian' => 17001, 'departamento_id' => 6],
            ['nombre' => '	AGUADAS	', 'codigo_dian' => 17013, 'departamento_id' => 6],
            ['nombre' => '	ANSERMA	', 'codigo_dian' => 17042, 'departamento_id' => 6],
            ['nombre' => '	ARANZAZU	', 'codigo_dian' => 17050, 'departamento_id' => 6],
            ['nombre' => '	BELALCAZAR	', 'codigo_dian' => 17088, 'departamento_id' => 6],
            ['nombre' => '	CHINCHINA	', 'codigo_dian' => 17174, 'departamento_id' => 6],
            ['nombre' => '	FILADELFIA	', 'codigo_dian' => 17272, 'departamento_id' => 6],
            ['nombre' => '	LA DORADA	', 'codigo_dian' => 17380, 'departamento_id' => 6],
            ['nombre' => '	LA MERCED	', 'codigo_dian' => 17388, 'departamento_id' => 6],
            ['nombre' => '	MANZANARES	', 'codigo_dian' => 17433, 'departamento_id' => 6],
            ['nombre' => '	MARMATO	', 'codigo_dian' => 17442, 'departamento_id' => 6],
            ['nombre' => '	MARQUETALIA	', 'codigo_dian' => 17444, 'departamento_id' => 6],
            ['nombre' => '	MARULANDA	', 'codigo_dian' => 17446, 'departamento_id' => 6],
            ['nombre' => '	NEIRA	', 'codigo_dian' => 17486, 'departamento_id' => 6],
            ['nombre' => '	NORCASIA	', 'codigo_dian' => 17495, 'departamento_id' => 6],
            ['nombre' => '	PACORA	', 'codigo_dian' => 17513, 'departamento_id' => 6],
            ['nombre' => '	PALESTINA	', 'codigo_dian' => 17524, 'departamento_id' => 6],
            ['nombre' => '	PENSILVANIA	', 'codigo_dian' => 17541, 'departamento_id' => 6],
            ['nombre' => '	RIOSUCIO	', 'codigo_dian' => 17614, 'departamento_id' => 6],
            ['nombre' => '	RISARALDA	', 'codigo_dian' => 17616, 'departamento_id' => 6],
            ['nombre' => '	SALAMINA	', 'codigo_dian' => 17653, 'departamento_id' => 6],
            ['nombre' => '	SAMANA	', 'codigo_dian' => 17662, 'departamento_id' => 6],
            ['nombre' => '	SAN JOSE	', 'codigo_dian' => 17665, 'departamento_id' => 6],
            ['nombre' => '	SUPIA	', 'codigo_dian' => 17777, 'departamento_id' => 6],
            ['nombre' => '	VICTORIA	', 'codigo_dian' => 17867, 'departamento_id' => 6],
            ['nombre' => '	VILLAMARIA	', 'codigo_dian' => 17873, 'departamento_id' => 6],
            ['nombre' => '	VITERBO	', 'codigo_dian' => 17877, 'departamento_id' => 6],
            ['nombre' => '	FLORENCIA	', 'codigo_dian' => 18001, 'departamento_id' => 7],
            ['nombre' => '	ALBANIA	', 'codigo_dian' => 18029, 'departamento_id' => 7],
            ['nombre' => '	BELEN ANDAQUIES	', 'codigo_dian' => 18094, 'departamento_id' => 7],
            ['nombre' => '	CARTAGENA DEL CHAIRA	', 'codigo_dian' => 18150, 'departamento_id' => 7],
            ['nombre' => '	CURILLO	', 'codigo_dian' => 18205, 'departamento_id' => 7],
            ['nombre' => '	EL DONCELLO	', 'codigo_dian' => 18247, 'departamento_id' => 7],
            ['nombre' => '	EL PAUJIL	', 'codigo_dian' => 18256, 'departamento_id' => 7],
            ['nombre' => '	LA MONTAÑITA	', 'codigo_dian' => 18410, 'departamento_id' => 7],
            ['nombre' => '	MILAN	', 'codigo_dian' => 18460, 'departamento_id' => 7],
            ['nombre' => '	MORELIA	', 'codigo_dian' => 18479, 'departamento_id' => 7],
            ['nombre' => '	PUERTO RICO	', 'codigo_dian' => 18592, 'departamento_id' => 7],
            ['nombre' => '	SAN JOSE DE FRAGUA	', 'codigo_dian' => 18610, 'departamento_id' => 7],
            ['nombre' => '	SAN  VICENTE DEL CAGUAN	', 'codigo_dian' => 18753, 'departamento_id' => 7],
            ['nombre' => '	SOLANO	', 'codigo_dian' => 18756, 'departamento_id' => 7],
            ['nombre' => '	SOLITA	', 'codigo_dian' => 18785, 'departamento_id' => 7],
            ['nombre' => '	VALPARAISO	', 'codigo_dian' => 18860, 'departamento_id' => 7],
            ['nombre' => '	POPAYAN	', 'codigo_dian' => 19001, 'departamento_id' => 8],
            ['nombre' => '	ALMAGUER	', 'codigo_dian' => 19022, 'departamento_id' => 8],
            ['nombre' => '	ARGELIA	', 'codigo_dian' => 19050, 'departamento_id' => 8],
            ['nombre' => '	BALBOA	', 'codigo_dian' => 19075, 'departamento_id' => 8],
            ['nombre' => '	BOLIVAR	', 'codigo_dian' => 19100, 'departamento_id' => 8],
            ['nombre' => '	BUENOS AIRES	', 'codigo_dian' => 19110, 'departamento_id' => 8],
            ['nombre' => '	CAJIBIO	', 'codigo_dian' => 19130, 'departamento_id' => 8],
            ['nombre' => '	CALDONO	', 'codigo_dian' => 19137, 'departamento_id' => 8],
            ['nombre' => '	CALOTO	', 'codigo_dian' => 19142, 'departamento_id' => 8],
            ['nombre' => '	CORINTO	', 'codigo_dian' => 19212, 'departamento_id' => 8],
            ['nombre' => '	EL TAMBO	', 'codigo_dian' => 19256, 'departamento_id' => 8],
            ['nombre' => '	FLORENCIA	', 'codigo_dian' => 19290, 'departamento_id' => 8],
            ['nombre' => '	GUAPI	', 'codigo_dian' => 19318, 'departamento_id' => 8],
            ['nombre' => '	INZA	', 'codigo_dian' => 19355, 'departamento_id' => 8],
            ['nombre' => '	JAMBALO	', 'codigo_dian' => 19364, 'departamento_id' => 8],
            ['nombre' => '	LA SIERRA	', 'codigo_dian' => 19392, 'departamento_id' => 8],
            ['nombre' => '	LA VEGA	', 'codigo_dian' => 19397, 'departamento_id' => 8],
            ['nombre' => '	LOPEZ	', 'codigo_dian' => 19418, 'departamento_id' => 8],
            ['nombre' => '	MERCADERES	', 'codigo_dian' => 19450, 'departamento_id' => 8],
            ['nombre' => '	MIRANDA	', 'codigo_dian' => 19455, 'departamento_id' => 8],
            ['nombre' => '	MORALES	', 'codigo_dian' => 19473, 'departamento_id' => 8],
            ['nombre' => '	PADILLA	', 'codigo_dian' => 19513, 'departamento_id' => 8],
            ['nombre' => '	PAEZ	', 'codigo_dian' => 19517, 'departamento_id' => 8],
            ['nombre' => '	PATIA(EL BORDO)	', 'codigo_dian' => 19532, 'departamento_id' => 8],
            ['nombre' => '	PIAMONTE	', 'codigo_dian' => 19533, 'departamento_id' => 8],
            ['nombre' => '	PIENDAMO	', 'codigo_dian' => 19548, 'departamento_id' => 8],
            ['nombre' => '	PUERTO TEJADA	', 'codigo_dian' => 19573, 'departamento_id' => 8],
            ['nombre' => '	PURACE	', 'codigo_dian' => 19585, 'departamento_id' => 8],
            ['nombre' => '	ROSAS	', 'codigo_dian' => 19622, 'departamento_id' => 8],
            ['nombre' => '	SAN SEBASTIAN	', 'codigo_dian' => 19693, 'departamento_id' => 8],
            ['nombre' => '	SANTANDER DE QUILICHAO	', 'codigo_dian' => 19698, 'departamento_id' => 8],
            ['nombre' => '	STA ROSA	', 'codigo_dian' => 19701, 'departamento_id' => 8],
            ['nombre' => '	SILVIA	', 'codigo_dian' => 19743, 'departamento_id' => 8],
            ['nombre' => '	SOTARA	', 'codigo_dian' => 19760, 'departamento_id' => 8],
            ['nombre' => '	SUAREZ	', 'codigo_dian' => 19780, 'departamento_id' => 8],
            ['nombre' => '	SUCRE	', 'codigo_dian' => 19785, 'departamento_id' => 8],
            ['nombre' => '	TIMBIO	', 'codigo_dian' => 19807, 'departamento_id' => 8],
            ['nombre' => '	TIMBIQUI	', 'codigo_dian' => 19809, 'departamento_id' => 8],
            ['nombre' => '	TORIBIO	', 'codigo_dian' => 19821, 'departamento_id' => 8],
            ['nombre' => '	TOTORO	', 'codigo_dian' => 19824, 'departamento_id' => 8],
            ['nombre' => '	VILLA RICA	', 'codigo_dian' => 19845, 'departamento_id' => 8],
            ['nombre' => '	VALLEDUPAR	', 'codigo_dian' => 20001, 'departamento_id' => 9],
            ['nombre' => '	AGUACHICA	', 'codigo_dian' => 20011, 'departamento_id' => 9],
            ['nombre' => '	AGUSTIN CODAZZI	', 'codigo_dian' => 20013, 'departamento_id' => 9],
            ['nombre' => '	ASTREA	', 'codigo_dian' => 20032, 'departamento_id' => 9],
            ['nombre' => '	BECERRIL	', 'codigo_dian' => 20045, 'departamento_id' => 9],
            ['nombre' => '	BOSCONIA	', 'codigo_dian' => 20060, 'departamento_id' => 9],
            ['nombre' => '	CHIMICHAGUA	', 'codigo_dian' => 20175, 'departamento_id' => 9],
            ['nombre' => '	CHIRIGUANA	', 'codigo_dian' => 20178, 'departamento_id' => 9],
            ['nombre' => '	CURUMANI	', 'codigo_dian' => 20228, 'departamento_id' => 9],
            ['nombre' => '	EL COPEY	', 'codigo_dian' => 20238, 'departamento_id' => 9],
            ['nombre' => '	EL PASO	', 'codigo_dian' => 20250, 'departamento_id' => 9],
            ['nombre' => '	GAMARRA	', 'codigo_dian' => 20295, 'departamento_id' => 9],
            ['nombre' => '	GONZALEZ	', 'codigo_dian' => 20310, 'departamento_id' => 9],
            ['nombre' => '	LA GLORIA	', 'codigo_dian' => 20383, 'departamento_id' => 9],
            ['nombre' => '	LA JAGUA IBIRICO	', 'codigo_dian' => 20400, 'departamento_id' => 9],
            ['nombre' => '	MANAURE BALCON DEL CESAR	', 'codigo_dian' => 20443, 'departamento_id' => 9],
            ['nombre' => '	PAILITAS	', 'codigo_dian' => 20517, 'departamento_id' => 9],
            ['nombre' => '	PELAYA	', 'codigo_dian' => 20550, 'departamento_id' => 9],
            ['nombre' => '	PUEBLO BELLO	', 'codigo_dian' => 20570, 'departamento_id' => 9],
            ['nombre' => '	RIO DE ORO	', 'codigo_dian' => 20614, 'departamento_id' => 9],
            ['nombre' => '	ROBLES (LA PAZ)	', 'codigo_dian' => 20621, 'departamento_id' => 9],
            ['nombre' => '	SAN ALBERTO	', 'codigo_dian' => 20710, 'departamento_id' => 9],
            ['nombre' => '	SAN DIEGO	', 'codigo_dian' => 20750, 'departamento_id' => 9],
            ['nombre' => '	SAN MARTIN	', 'codigo_dian' => 20770, 'departamento_id' => 9],
            ['nombre' => '	TAMALAMEQUE	', 'codigo_dian' => 20787, 'departamento_id' => 9],
            ['nombre' => '	MONTERIA	', 'codigo_dian' => 23001, 'departamento_id' => 10],
            ['nombre' => '	AYAPEL	', 'codigo_dian' => 23068, 'departamento_id' => 10],
            ['nombre' => '	BUENAVISTA	', 'codigo_dian' => 23079, 'departamento_id' => 10],
            ['nombre' => '	CANALETE	', 'codigo_dian' => 23090, 'departamento_id' => 10],
            ['nombre' => '	CERETE	', 'codigo_dian' => 23162, 'departamento_id' => 10],
            ['nombre' => '	CHIMA	', 'codigo_dian' => 23168, 'departamento_id' => 10],
            ['nombre' => '	CHINU	', 'codigo_dian' => 23182, 'departamento_id' => 10],
            ['nombre' => '	CIENAGA DE ORO	', 'codigo_dian' => 23189, 'departamento_id' => 10],
            ['nombre' => '	COTORRA	', 'codigo_dian' => 23300, 'departamento_id' => 10],
            ['nombre' => '	LA APARTADA	', 'codigo_dian' => 23350, 'departamento_id' => 10],
            ['nombre' => '	LORICA	', 'codigo_dian' => 23417, 'departamento_id' => 10],
            ['nombre' => '	LOS CORDOBAS	', 'codigo_dian' => 23419, 'departamento_id' => 10],
            ['nombre' => '	MOMIL	', 'codigo_dian' => 23464, 'departamento_id' => 10],
            ['nombre' => '	MONTELIBANO	', 'codigo_dian' => 23466, 'departamento_id' => 10],
            ['nombre' => '	MOÑITOS	', 'codigo_dian' => 23500, 'departamento_id' => 10],
            ['nombre' => '	PLANETA RICA	', 'codigo_dian' => 23555, 'departamento_id' => 10],
            ['nombre' => '	PUEBLO NUEVO	', 'codigo_dian' => 23570, 'departamento_id' => 10],
            ['nombre' => '	PUERTO ESCONDIDO	', 'codigo_dian' => 23574, 'departamento_id' => 10],
            ['nombre' => '	PUERTO LIBERTADOR	', 'codigo_dian' => 23580, 'departamento_id' => 10],
            ['nombre' => '	PURISIMA	', 'codigo_dian' => 23586, 'departamento_id' => 10],
            ['nombre' => '	SAHAGUN	', 'codigo_dian' => 23660, 'departamento_id' => 10],
            ['nombre' => '	SAN ANDRES SOTAVENTO	', 'codigo_dian' => 23670, 'departamento_id' => 10],
            ['nombre' => '	SAN ANTERO	', 'codigo_dian' => 23672, 'departamento_id' => 10],
            ['nombre' => '	SAN BERNARDO VIENTO	', 'codigo_dian' => 23675, 'departamento_id' => 10],
            ['nombre' => '	SAN CARLOS	', 'codigo_dian' => 23678, 'departamento_id' => 10],
            ['nombre' => '	SAN PELAYO	', 'codigo_dian' => 23686, 'departamento_id' => 10],
            ['nombre' => '	TIERRALTA	', 'codigo_dian' => 23807, 'departamento_id' => 10],
            ['nombre' => '	VALENCIA	', 'codigo_dian' => 23855, 'departamento_id' => 10],
            ['nombre' => '	AGUA DE DIOS	', 'codigo_dian' => 25001, 'departamento_id' => 11],
            ['nombre' => '	ALBAN	', 'codigo_dian' => 25019, 'departamento_id' => 11],
            ['nombre' => '	ANAPOIMA	', 'codigo_dian' => 25035, 'departamento_id' => 11],
            ['nombre' => '	ANOLAIMA	', 'codigo_dian' => 25040, 'departamento_id' => 11],
            ['nombre' => '	ARBELAEZ	', 'codigo_dian' => 25053, 'departamento_id' => 11],
            ['nombre' => '	BELTRAN	', 'codigo_dian' => 25086, 'departamento_id' => 11],
            ['nombre' => '	BITUIMA	', 'codigo_dian' => 25095, 'departamento_id' => 11],
            ['nombre' => '	BOJACA	', 'codigo_dian' => 25099, 'departamento_id' => 11],
            ['nombre' => '	CABRERA	', 'codigo_dian' => 25120, 'departamento_id' => 11],
            ['nombre' => '	CACHIPAY	', 'codigo_dian' => 25123, 'departamento_id' => 11],
            ['nombre' => '	CAJICA	', 'codigo_dian' => 25126, 'departamento_id' => 11],
            ['nombre' => '	CAPARRAPI	', 'codigo_dian' => 25148, 'departamento_id' => 11],
            ['nombre' => '	CAQUEZA	', 'codigo_dian' => 25151, 'departamento_id' => 11],
            ['nombre' => '	CARMEN DE CARUPA	', 'codigo_dian' => 25154, 'departamento_id' => 11],
            ['nombre' => '	CHAGUANI	', 'codigo_dian' => 25168, 'departamento_id' => 11],
            ['nombre' => '	CHIA	', 'codigo_dian' => 25175, 'departamento_id' => 11],
            ['nombre' => '	CHIPAQUE	', 'codigo_dian' => 25178, 'departamento_id' => 11],
            ['nombre' => '	CHOACHI	', 'codigo_dian' => 25181, 'departamento_id' => 11],
            ['nombre' => '	CHOCONTA	', 'codigo_dian' => 25183, 'departamento_id' => 11],
            ['nombre' => '	COGUA	', 'codigo_dian' => 25200, 'departamento_id' => 11],
            ['nombre' => '	COTA	', 'codigo_dian' => 25214, 'departamento_id' => 11],
            ['nombre' => '	CUCUNUBA	', 'codigo_dian' => 25224, 'departamento_id' => 11],
            ['nombre' => '	EL COLEGIO	', 'codigo_dian' => 25245, 'departamento_id' => 11],
            ['nombre' => '	EL PEÑON	', 'codigo_dian' => 25258, 'departamento_id' => 11],
            ['nombre' => '	EL ROSAL	', 'codigo_dian' => 25260, 'departamento_id' => 11],
            ['nombre' => '	FACATATIVA	', 'codigo_dian' => 25269, 'departamento_id' => 11],
            ['nombre' => '	FOMEQUE	', 'codigo_dian' => 25279, 'departamento_id' => 11],
            ['nombre' => '	FOSCA	', 'codigo_dian' => 25281, 'departamento_id' => 11],
            ['nombre' => '	FUNZA	', 'codigo_dian' => 25286, 'departamento_id' => 11],
            ['nombre' => '	FUQUENE	', 'codigo_dian' => 25288, 'departamento_id' => 11],
            ['nombre' => '	FUSAGASUGA	', 'codigo_dian' => 25290, 'departamento_id' => 11],
            ['nombre' => '	GACHALA	', 'codigo_dian' => 25293, 'departamento_id' => 11],
            ['nombre' => '	GACHANCIPA	', 'codigo_dian' => 25295, 'departamento_id' => 11],
            ['nombre' => '	GACHETA	', 'codigo_dian' => 25297, 'departamento_id' => 11],
            ['nombre' => '	GAMA	', 'codigo_dian' => 25299, 'departamento_id' => 11],
            ['nombre' => '	GIRARDOT	', 'codigo_dian' => 25307, 'departamento_id' => 11],
            ['nombre' => '	GRANADA	', 'codigo_dian' => 25312, 'departamento_id' => 11],
            ['nombre' => '	GUACHETA	', 'codigo_dian' => 25317, 'departamento_id' => 11],
            ['nombre' => '	GUADUAS	', 'codigo_dian' => 25320, 'departamento_id' => 11],
            ['nombre' => '	GUASCA	', 'codigo_dian' => 25322, 'departamento_id' => 11],
            ['nombre' => '	GUATAQUI	', 'codigo_dian' => 25324, 'departamento_id' => 11],
            ['nombre' => '	GUATAVITA	', 'codigo_dian' => 25326, 'departamento_id' => 11],
            ['nombre' => '	GUAYABAL DE SIQUIMA	', 'codigo_dian' => 25328, 'departamento_id' => 11],
            ['nombre' => '	GUAYABETAL	', 'codigo_dian' => 25335, 'departamento_id' => 11],
            ['nombre' => '	GUTIERREZ	', 'codigo_dian' => 25339, 'departamento_id' => 11],
            ['nombre' => '	JERUSALEN	', 'codigo_dian' => 25368, 'departamento_id' => 11],
            ['nombre' => '	JUNIN	', 'codigo_dian' => 25372, 'departamento_id' => 11],
            ['nombre' => '	LA CALERA	', 'codigo_dian' => 25377, 'departamento_id' => 11],
            ['nombre' => '	LA MESA	', 'codigo_dian' => 25386, 'departamento_id' => 11],
            ['nombre' => '	LA PALMA	', 'codigo_dian' => 25394, 'departamento_id' => 11],
            ['nombre' => '	LA PEÑA	', 'codigo_dian' => 25398, 'departamento_id' => 11],
            ['nombre' => '	LA VEGA	', 'codigo_dian' => 25402, 'departamento_id' => 11],
            ['nombre' => '	LENGUAZAQUE	', 'codigo_dian' => 25407, 'departamento_id' => 11],
            ['nombre' => '	MACHETA	', 'codigo_dian' => 25426, 'departamento_id' => 11],
            ['nombre' => '	MADRID	', 'codigo_dian' => 25430, 'departamento_id' => 11],
            ['nombre' => '	MANTA	', 'codigo_dian' => 25436, 'departamento_id' => 11],
            ['nombre' => '	MEDINA	', 'codigo_dian' => 25438, 'departamento_id' => 11],
            ['nombre' => '	MOSQUERA	', 'codigo_dian' => 25473, 'departamento_id' => 11],
            ['nombre' => '	NARIÑO	', 'codigo_dian' => 25483, 'departamento_id' => 11],
            ['nombre' => '	NEMOCON	', 'codigo_dian' => 25486, 'departamento_id' => 11],
            ['nombre' => '	NILO	', 'codigo_dian' => 25488, 'departamento_id' => 11],
            ['nombre' => '	NIMAIMA	', 'codigo_dian' => 25489, 'departamento_id' => 11],
            ['nombre' => '	NOCAIMA	', 'codigo_dian' => 25491, 'departamento_id' => 11],
            ['nombre' => '	VENECIA (OSPINA PEREZ)	', 'codigo_dian' => 25506, 'departamento_id' => 11],
            ['nombre' => '	PACHO	', 'codigo_dian' => 25513, 'departamento_id' => 11],
            ['nombre' => '	PAIME	', 'codigo_dian' => 25518, 'departamento_id' => 11],
            ['nombre' => '	PANDI	', 'codigo_dian' => 25524, 'departamento_id' => 11],
            ['nombre' => '	PARATEBUENO	', 'codigo_dian' => 25530, 'departamento_id' => 11],
            ['nombre' => '	PASCA	', 'codigo_dian' => 25535, 'departamento_id' => 11],
            ['nombre' => '	PUERTO SALGAR	', 'codigo_dian' => 25572, 'departamento_id' => 11],
            ['nombre' => '	PULI	', 'codigo_dian' => 25580, 'departamento_id' => 11],
            ['nombre' => '	QUEBRADANEGRA	', 'codigo_dian' => 25592, 'departamento_id' => 11],
            ['nombre' => '	QUETAME	', 'codigo_dian' => 25594, 'departamento_id' => 11],
            ['nombre' => '	QUIPILE	', 'codigo_dian' => 25596, 'departamento_id' => 11],
            ['nombre' => '	RAFAEL REYES	', 'codigo_dian' => 25599, 'departamento_id' => 11],
            ['nombre' => '	RICAURTE	', 'codigo_dian' => 25612, 'departamento_id' => 11],
            ['nombre' => '	SAN  ANTONIO DEL  TEQUENDAMA	', 'codigo_dian' => 25645, 'departamento_id' => 11],
            ['nombre' => '	SAN BERNARDO	', 'codigo_dian' => 25649, 'departamento_id' => 11],
            ['nombre' => '	SAN CAYETANO	', 'codigo_dian' => 25653, 'departamento_id' => 11],
            ['nombre' => '	SAN FRANCISCO	', 'codigo_dian' => 25658, 'departamento_id' => 11],
            ['nombre' => '	SAN JUAN DE RIOSECO	', 'codigo_dian' => 25662, 'departamento_id' => 11],
            ['nombre' => '	SASAIMA	', 'codigo_dian' => 25718, 'departamento_id' => 11],
            ['nombre' => '	SESQUILE	', 'codigo_dian' => 25736, 'departamento_id' => 11],
            ['nombre' => '	SIBATE	', 'codigo_dian' => 25740, 'departamento_id' => 11],
            ['nombre' => '	SILVANIA	', 'codigo_dian' => 25743, 'departamento_id' => 11],
            ['nombre' => '	SIMIJACA	', 'codigo_dian' => 25745, 'departamento_id' => 11],
            ['nombre' => '	SOACHA	', 'codigo_dian' => 25754, 'departamento_id' => 11],
            ['nombre' => '	SOPO	', 'codigo_dian' => 25758, 'departamento_id' => 11],
            ['nombre' => '	SUBACHOQUE	', 'codigo_dian' => 25769, 'departamento_id' => 11],
            ['nombre' => '	SUESCA	', 'codigo_dian' => 25772, 'departamento_id' => 11],
            ['nombre' => '	SUPATA	', 'codigo_dian' => 25777, 'departamento_id' => 11],
            ['nombre' => '	SUSA	', 'codigo_dian' => 25779, 'departamento_id' => 11],
            ['nombre' => '	SUTATAUSA	', 'codigo_dian' => 25781, 'departamento_id' => 11],
            ['nombre' => '	TABIO	', 'codigo_dian' => 25785, 'departamento_id' => 11],
            ['nombre' => '	TAUSA	', 'codigo_dian' => 25793, 'departamento_id' => 11],
            ['nombre' => '	TENA	', 'codigo_dian' => 25797, 'departamento_id' => 11],
            ['nombre' => '	TENJO	', 'codigo_dian' => 25799, 'departamento_id' => 11],
            ['nombre' => '	TIBACUY	', 'codigo_dian' => 25805, 'departamento_id' => 11],
            ['nombre' => '	TIBIRITA	', 'codigo_dian' => 25807, 'departamento_id' => 11],
            ['nombre' => '	TOCAIMA	', 'codigo_dian' => 25815, 'departamento_id' => 11],
            ['nombre' => '	TOCANCIPA	', 'codigo_dian' => 25817, 'departamento_id' => 11],
            ['nombre' => '	TOPAIPI	', 'codigo_dian' => 25823, 'departamento_id' => 11],
            ['nombre' => '	UBALA	', 'codigo_dian' => 25839, 'departamento_id' => 11],
            ['nombre' => '	UBAQUE	', 'codigo_dian' => 25841, 'departamento_id' => 11],
            ['nombre' => '	UBATE	', 'codigo_dian' => 25843, 'departamento_id' => 11],
            ['nombre' => '	UNE	', 'codigo_dian' => 25845, 'departamento_id' => 11],
            ['nombre' => '	UTICA	', 'codigo_dian' => 25851, 'departamento_id' => 11],
            ['nombre' => '	VERGARA	', 'codigo_dian' => 25862, 'departamento_id' => 11],
            ['nombre' => '	VIANI	', 'codigo_dian' => 25867, 'departamento_id' => 11],
            ['nombre' => '	VILLAGOMEZ	', 'codigo_dian' => 25871, 'departamento_id' => 11],
            ['nombre' => '	VILLAPINZON	', 'codigo_dian' => 25873, 'departamento_id' => 11],
            ['nombre' => '	VILLETA	', 'codigo_dian' => 25875, 'departamento_id' => 11],
            ['nombre' => '	VIOTA	', 'codigo_dian' => 25878, 'departamento_id' => 11],
            ['nombre' => '	YACOPI	', 'codigo_dian' => 25885, 'departamento_id' => 11],
            ['nombre' => '	ZIPACON	', 'codigo_dian' => 25898, 'departamento_id' => 11],
            ['nombre' => '	ZIPAQUIRA	', 'codigo_dian' => 25899, 'departamento_id' => 11],
            ['nombre' => '	QUIBDO	', 'codigo_dian' => 27001, 'departamento_id' => 12],
            ['nombre' => '	ACANDI	', 'codigo_dian' => 27006, 'departamento_id' => 12],
            ['nombre' => '	ALTO BAUDO (PIE DE PATO)	', 'codigo_dian' => 27025, 'departamento_id' => 12],
            ['nombre' => '	ATRATO	', 'codigo_dian' => 27050, 'departamento_id' => 12],
            ['nombre' => '	BAGADO	', 'codigo_dian' => 27073, 'departamento_id' => 12],
            ['nombre' => '	BAHIA SOLANO (MUTIS)	', 'codigo_dian' => 27075, 'departamento_id' => 12],
            ['nombre' => '	BAJO BAUDO (PIZARRO)	', 'codigo_dian' => 27077, 'departamento_id' => 12],
            ['nombre' => '	BOJAYA (BELLAVISTA)	', 'codigo_dian' => 27099, 'departamento_id' => 12],
            ['nombre' => '	CANTON DE SAN PABLO	', 'codigo_dian' => 27135, 'departamento_id' => 12],
            ['nombre' => '	CARMEN DEL DARIEN	', 'codigo_dian' => 27150, 'departamento_id' => 12],
            ['nombre' => '	CERTEGUI	', 'codigo_dian' => 27160, 'departamento_id' => 12],
            ['nombre' => '	CONDOTO	', 'codigo_dian' => 27205, 'departamento_id' => 12],
            ['nombre' => '	EL CARMEN	', 'codigo_dian' => 27245, 'departamento_id' => 12],
            ['nombre' => '	LITORAL DEL SAN JUAN	', 'codigo_dian' => 27250, 'departamento_id' => 12],
            ['nombre' => '	ISTMINA	', 'codigo_dian' => 27361, 'departamento_id' => 12],
            ['nombre' => '	JURADO	', 'codigo_dian' => 27372, 'departamento_id' => 12],
            ['nombre' => '	LLORO	', 'codigo_dian' => 27413, 'departamento_id' => 12],
            ['nombre' => '	MEDIO ATRATO	', 'codigo_dian' => 27425, 'departamento_id' => 12],
            ['nombre' => '	MEDIO BAUDO (BOCA DE PEPE)	', 'codigo_dian' => 27430, 'departamento_id' => 12],
            ['nombre' => '	MEDIO SAN JUAN	', 'codigo_dian' => 27450, 'departamento_id' => 12],
            ['nombre' => '	NOVITA	', 'codigo_dian' => 27491, 'departamento_id' => 12],
            ['nombre' => '	NUQUI	', 'codigo_dian' => 27495, 'departamento_id' => 12],
            ['nombre' => '	RIO IRO	', 'codigo_dian' => 27580, 'departamento_id' => 12],
            ['nombre' => '	RIO QUITO	', 'codigo_dian' => 27600, 'departamento_id' => 12],
            ['nombre' => '	RIOSUCIO	', 'codigo_dian' => 27615, 'departamento_id' => 12],
            ['nombre' => '	SAN JOSE DEL PALMAR	', 'codigo_dian' => 27660, 'departamento_id' => 12],
            ['nombre' => '	SIPI	', 'codigo_dian' => 27745, 'departamento_id' => 12],
            ['nombre' => '	TADO	', 'codigo_dian' => 27787, 'departamento_id' => 12],
            ['nombre' => '	UNGUIA	', 'codigo_dian' => 27800, 'departamento_id' => 12],
            ['nombre' => '	UNION PANAMERICANA	', 'codigo_dian' => 27810, 'departamento_id' => 12],
            ['nombre' => '	NEIVA	', 'codigo_dian' => 41001, 'departamento_id' => 13],
            ['nombre' => '	ACEVEDO	', 'codigo_dian' => 41006, 'departamento_id' => 13],
            ['nombre' => '	AGRADO	', 'codigo_dian' => 41013, 'departamento_id' => 13],
            ['nombre' => '	AIPE	', 'codigo_dian' => 41016, 'departamento_id' => 13],
            ['nombre' => '	ALGECIRAS	', 'codigo_dian' => 41020, 'departamento_id' => 13],
            ['nombre' => '	ALTAMIRA	', 'codigo_dian' => 41026, 'departamento_id' => 13],
            ['nombre' => '	BARAYA	', 'codigo_dian' => 41078, 'departamento_id' => 13],
            ['nombre' => '	CAMPOALEGRE	', 'codigo_dian' => 41132, 'departamento_id' => 13],
            ['nombre' => '	COLOMBIA	', 'codigo_dian' => 41206, 'departamento_id' => 13],
            ['nombre' => '	ELIAS	', 'codigo_dian' => 41244, 'departamento_id' => 13],
            ['nombre' => '	GARZON	', 'codigo_dian' => 41298, 'departamento_id' => 13],
            ['nombre' => '	GIGANTE	', 'codigo_dian' => 41306, 'departamento_id' => 13],
            ['nombre' => '	GUADALUPE	', 'codigo_dian' => 41319, 'departamento_id' => 13],
            ['nombre' => '	HOBO	', 'codigo_dian' => 41349, 'departamento_id' => 13],
            ['nombre' => '	IQUIRA	', 'codigo_dian' => 41357, 'departamento_id' => 13],
            ['nombre' => '	ISNOS	', 'codigo_dian' => 41359, 'departamento_id' => 13],
            ['nombre' => '	LA ARGENTINA	', 'codigo_dian' => 41378, 'departamento_id' => 13],
            ['nombre' => '	LA PLATA	', 'codigo_dian' => 41396, 'departamento_id' => 13],
            ['nombre' => '	NATAGA	', 'codigo_dian' => 41483, 'departamento_id' => 13],
            ['nombre' => '	OPORAPA	', 'codigo_dian' => 41503, 'departamento_id' => 13],
            ['nombre' => '	PAICOL	', 'codigo_dian' => 41518, 'departamento_id' => 13],
            ['nombre' => '	PALERMO	', 'codigo_dian' => 41524, 'departamento_id' => 13],
            ['nombre' => '	PALESTINA	', 'codigo_dian' => 41530, 'departamento_id' => 13],
            ['nombre' => '	PITAL	', 'codigo_dian' => 41548, 'departamento_id' => 13],
            ['nombre' => '	PITALITO	', 'codigo_dian' => 41551, 'departamento_id' => 13],
            ['nombre' => '	RIVERA	', 'codigo_dian' => 41615, 'departamento_id' => 13],
            ['nombre' => '	SALADOBLANCO	', 'codigo_dian' => 41660, 'departamento_id' => 13],
            ['nombre' => '	SAN AGUSTIN	', 'codigo_dian' => 41668, 'departamento_id' => 13],
            ['nombre' => '	SANTA MARIA	', 'codigo_dian' => 41676, 'departamento_id' => 13],
            ['nombre' => '	SUAZA	', 'codigo_dian' => 41770, 'departamento_id' => 13],
            ['nombre' => '	TARQUI	', 'codigo_dian' => 41791, 'departamento_id' => 13],
            ['nombre' => '	TESALIA	', 'codigo_dian' => 41797, 'departamento_id' => 13],
            ['nombre' => '	TELLO	', 'codigo_dian' => 41799, 'departamento_id' => 13],
            ['nombre' => '	TERUEL	', 'codigo_dian' => 41801, 'departamento_id' => 13],
            ['nombre' => '	TIMANA	', 'codigo_dian' => 41807, 'departamento_id' => 13],
            ['nombre' => '	VILLAVIEJA	', 'codigo_dian' => 41872, 'departamento_id' => 13],
            ['nombre' => '	YAGUARA	', 'codigo_dian' => 41885, 'departamento_id' => 13],
            ['nombre' => '	RIOHACHA	', 'codigo_dian' => 44001, 'departamento_id' => 14],
            ['nombre' => '	ALBANIA	', 'codigo_dian' => 44035, 'departamento_id' => 14],
            ['nombre' => '	BARRANCAS	', 'codigo_dian' => 44078, 'departamento_id' => 14],
            ['nombre' => '	DIBULLA	', 'codigo_dian' => 44090, 'departamento_id' => 14],
            ['nombre' => '	DISTRACCION	', 'codigo_dian' => 44098, 'departamento_id' => 14],
            ['nombre' => '	EL MOLINO	', 'codigo_dian' => 44110, 'departamento_id' => 14],
            ['nombre' => '	FONSECA	', 'codigo_dian' => 44279, 'departamento_id' => 14],
            ['nombre' => '	HATONUEVO	', 'codigo_dian' => 44378, 'departamento_id' => 14],
            ['nombre' => '	LA JAGUA DEL PILAR	', 'codigo_dian' => 44420, 'departamento_id' => 14],
            ['nombre' => '	MAICAO	', 'codigo_dian' => 44430, 'departamento_id' => 14],
            ['nombre' => '	MANAURE	', 'codigo_dian' => 44560, 'departamento_id' => 14],
            ['nombre' => '	SAN JUAN DEL CESAR	', 'codigo_dian' => 44650, 'departamento_id' => 14],
            ['nombre' => '	URIBIA	', 'codigo_dian' => 44847, 'departamento_id' => 14],
            ['nombre' => '	URUMITA	', 'codigo_dian' => 44855, 'departamento_id' => 14],
            ['nombre' => '	VILLANUEVA	', 'codigo_dian' => 44874, 'departamento_id' => 14],
            ['nombre' => '	SANTA MARTA	', 'codigo_dian' => 47001, 'departamento_id' => 15],
            ['nombre' => '	ALGARROBO	', 'codigo_dian' => 47030, 'departamento_id' => 15],
            ['nombre' => '	ARACATACA	', 'codigo_dian' => 47053, 'departamento_id' => 15],
            ['nombre' => '	ARIGUANI	', 'codigo_dian' => 47058, 'departamento_id' => 15],
            ['nombre' => '	CERRO SAN ANTONIO	', 'codigo_dian' => 47161, 'departamento_id' => 15],
            ['nombre' => '	CHIVOLO	', 'codigo_dian' => 47170, 'departamento_id' => 15],
            ['nombre' => '	CIENAGA	', 'codigo_dian' => 47189, 'departamento_id' => 15],
            ['nombre' => '	CONCORDIA	', 'codigo_dian' => 47205, 'departamento_id' => 15],
            ['nombre' => '	EL BANCO	', 'codigo_dian' => 47245, 'departamento_id' => 15],
            ['nombre' => '	EL PIÑON	', 'codigo_dian' => 47258, 'departamento_id' => 15],
            ['nombre' => '	EL RETEN	', 'codigo_dian' => 47268, 'departamento_id' => 15],
            ['nombre' => '	FUNDACION	', 'codigo_dian' => 47288, 'departamento_id' => 15],
            ['nombre' => '	GUAMAL	', 'codigo_dian' => 47318, 'departamento_id' => 15],
            ['nombre' => '	NUEVA GRANADA	', 'codigo_dian' => 47460, 'departamento_id' => 15],
            ['nombre' => '	PEDRAZA	', 'codigo_dian' => 47541, 'departamento_id' => 15],
            ['nombre' => '	PIJIÑO DEL CARMEN	', 'codigo_dian' => 47545, 'departamento_id' => 15],
            ['nombre' => '	PIVIJAY	', 'codigo_dian' => 47551, 'departamento_id' => 15],
            ['nombre' => '	PLATO	', 'codigo_dian' => 47555, 'departamento_id' => 15],
            ['nombre' => '	PUEBLOVIEJO	', 'codigo_dian' => 47570, 'departamento_id' => 15],
            ['nombre' => '	REMOLINO	', 'codigo_dian' => 47605, 'departamento_id' => 15],
            ['nombre' => '	SABANAS DE SAN ANGEL	', 'codigo_dian' => 47660, 'departamento_id' => 15],
            ['nombre' => '	SALAMINA	', 'codigo_dian' => 47675, 'departamento_id' => 15],
            ['nombre' => '	SAN SEBASTIAN DE BUENAVISTA	', 'codigo_dian' => 47692, 'departamento_id' => 15],
            ['nombre' => '	SAN ZENON	', 'codigo_dian' => 47703, 'departamento_id' => 15],
            ['nombre' => '	SANTA ANA	', 'codigo_dian' => 47707, 'departamento_id' => 15],
            ['nombre' => '	SANTA BARBARA DE PINTO	', 'codigo_dian' => 47720, 'departamento_id' => 15],
            ['nombre' => '	SITIONUEVO	', 'codigo_dian' => 47745, 'departamento_id' => 15],
            ['nombre' => '	TENERIFE	', 'codigo_dian' => 47798, 'departamento_id' => 15],
            ['nombre' => '	ZAPAYAN	', 'codigo_dian' => 47960, 'departamento_id' => 15],
            ['nombre' => '	ZONA BANANERA	', 'codigo_dian' => 47980, 'departamento_id' => 15],
            ['nombre' => '	VILLAVICENCIO	', 'codigo_dian' => 50001, 'departamento_id' => 16],
            ['nombre' => '	ACACIAS	', 'codigo_dian' => 50006, 'departamento_id' => 16],
            ['nombre' => '	BARRANCA DE UPIA	', 'codigo_dian' => 50110, 'departamento_id' => 16],
            ['nombre' => '	CABUYARO	', 'codigo_dian' => 50124, 'departamento_id' => 16],
            ['nombre' => '	CASTILLA LA NUEVA	', 'codigo_dian' => 50150, 'departamento_id' => 16],
            ['nombre' => '	CUBARRAL	', 'codigo_dian' => 50223, 'departamento_id' => 16],
            ['nombre' => '	CUMARAL	', 'codigo_dian' => 50226, 'departamento_id' => 16],
            ['nombre' => '	EL CALVARIO	', 'codigo_dian' => 50245, 'departamento_id' => 16],
            ['nombre' => '	EL CASTILLO	', 'codigo_dian' => 50251, 'departamento_id' => 16],
            ['nombre' => '	EL DORADO	', 'codigo_dian' => 50270, 'departamento_id' => 16],
            ['nombre' => '	FUENTE DE ORO	', 'codigo_dian' => 50287, 'departamento_id' => 16],
            ['nombre' => '	GRANADA	', 'codigo_dian' => 50313, 'departamento_id' => 16],
            ['nombre' => '	GUAMAL	', 'codigo_dian' => 50318, 'departamento_id' => 16],
            ['nombre' => '	MAPIRIPAN	', 'codigo_dian' => 50325, 'departamento_id' => 16],
            ['nombre' => '	MESETAS	', 'codigo_dian' => 50330, 'departamento_id' => 16],
            ['nombre' => '	LA MACARENA	', 'codigo_dian' => 50350, 'departamento_id' => 16],
            ['nombre' => '	LA URIBE	', 'codigo_dian' => 50370, 'departamento_id' => 16],
            ['nombre' => '	LEJANIAS	', 'codigo_dian' => 50400, 'departamento_id' => 16],
            ['nombre' => '	PUERTO CONCORDIA	', 'codigo_dian' => 50450, 'departamento_id' => 16],
            ['nombre' => '	PUERTO GAITAN	', 'codigo_dian' => 50568, 'departamento_id' => 16],
            ['nombre' => '	PUERTO LOPEZ	', 'codigo_dian' => 50573, 'departamento_id' => 16],
            ['nombre' => '	PUERTO LLERAS	', 'codigo_dian' => 50577, 'departamento_id' => 16],
            ['nombre' => '	PUERTO RICO	', 'codigo_dian' => 50590, 'departamento_id' => 16],
            ['nombre' => '	RESTREPO	', 'codigo_dian' => 50606, 'departamento_id' => 16],
            ['nombre' => '	SAN CARLOS GUAROA	', 'codigo_dian' => 50680, 'departamento_id' => 16],
            ['nombre' => '	SAN  JUAN DE ARAMA	', 'codigo_dian' => 50683, 'departamento_id' => 16],
            ['nombre' => '	SAN JUANITO	', 'codigo_dian' => 50686, 'departamento_id' => 16],
            ['nombre' => '	SAN MARTIN	', 'codigo_dian' => 50689, 'departamento_id' => 16],
            ['nombre' => '	VISTA HERMOSA	', 'codigo_dian' => 50711, 'departamento_id' => 16],
            ['nombre' => '	PASTO	', 'codigo_dian' => 52001, 'departamento_id' => 17],
            ['nombre' => '	ALBAN	', 'codigo_dian' => 52019, 'departamento_id' => 17],
            ['nombre' => '	ALDAÑA	', 'codigo_dian' => 52022, 'departamento_id' => 17],
            ['nombre' => '	ANCUYA	', 'codigo_dian' => 52036, 'departamento_id' => 17],
            ['nombre' => '	ARBOLEDA	', 'codigo_dian' => 52051, 'departamento_id' => 17],
            ['nombre' => '	BARBACOAS	', 'codigo_dian' => 52079, 'departamento_id' => 17],
            ['nombre' => '	BELEN	', 'codigo_dian' => 52083, 'departamento_id' => 17],
            ['nombre' => '	BUESACO	', 'codigo_dian' => 52110, 'departamento_id' => 17],
            ['nombre' => '	COLON(GENOVA)	', 'codigo_dian' => 52203, 'departamento_id' => 17],
            ['nombre' => '	CONSACA	', 'codigo_dian' => 52207, 'departamento_id' => 17],
            ['nombre' => '	CONTADERO	', 'codigo_dian' => 52210, 'departamento_id' => 17],
            ['nombre' => '	CORDOBA	', 'codigo_dian' => 52215, 'departamento_id' => 17],
            ['nombre' => '	CUASPUD	', 'codigo_dian' => 52224, 'departamento_id' => 17],
            ['nombre' => '	CUMBAL	', 'codigo_dian' => 52227, 'departamento_id' => 17],
            ['nombre' => '	CUMBITARA	', 'codigo_dian' => 52233, 'departamento_id' => 17],
            ['nombre' => '	CHACHAGUI	', 'codigo_dian' => 52240, 'departamento_id' => 17],
            ['nombre' => '	EL CHARCO	', 'codigo_dian' => 52250, 'departamento_id' => 17],
            ['nombre' => '	EL PEÑOL	', 'codigo_dian' => 52254, 'departamento_id' => 17],
            ['nombre' => '	EL ROSARIO	', 'codigo_dian' => 52256, 'departamento_id' => 17],
            ['nombre' => '	EL TABLON	', 'codigo_dian' => 52258, 'departamento_id' => 17],
            ['nombre' => '	EL TAMBO	', 'codigo_dian' => 52260, 'departamento_id' => 17],
            ['nombre' => '	FUNES	', 'codigo_dian' => 52287, 'departamento_id' => 17],
            ['nombre' => '	GUACHUCAL	', 'codigo_dian' => 52317, 'departamento_id' => 17],
            ['nombre' => '	GUAITARILLA	', 'codigo_dian' => 52320, 'departamento_id' => 17],
            ['nombre' => '	GUALMATAN	', 'codigo_dian' => 52323, 'departamento_id' => 17],
            ['nombre' => '	ILES	', 'codigo_dian' => 52352, 'departamento_id' => 17],
            ['nombre' => '	IMUES	', 'codigo_dian' => 52354, 'departamento_id' => 17],
            ['nombre' => '	IPIALES	', 'codigo_dian' => 52356, 'departamento_id' => 17],
            ['nombre' => '	LA CRUZ	', 'codigo_dian' => 52378, 'departamento_id' => 17],
            ['nombre' => '	LA FLORIDA	', 'codigo_dian' => 52381, 'departamento_id' => 17],
            ['nombre' => '	LA LLANADA	', 'codigo_dian' => 52385, 'departamento_id' => 17],
            ['nombre' => '	LA TOLA	', 'codigo_dian' => 52390, 'departamento_id' => 17],
            ['nombre' => '	LA UNION	', 'codigo_dian' => 52399, 'departamento_id' => 17],
            ['nombre' => '	LEIVA	', 'codigo_dian' => 52405, 'departamento_id' => 17],
            ['nombre' => '	LINARES	', 'codigo_dian' => 52411, 'departamento_id' => 17],
            ['nombre' => '	LOS ANDES	', 'codigo_dian' => 52418, 'departamento_id' => 17],
            ['nombre' => '	MAGUI	', 'codigo_dian' => 52427, 'departamento_id' => 17],
            ['nombre' => '	MALLAMA	', 'codigo_dian' => 52435, 'departamento_id' => 17],
            ['nombre' => '	MOSQUERA	', 'codigo_dian' => 52473, 'departamento_id' => 17],
            ['nombre' => '	NARIÑO	', 'codigo_dian' => 52480, 'departamento_id' => 17],
            ['nombre' => '	OLAYA HERRERA	', 'codigo_dian' => 52490, 'departamento_id' => 17],
            ['nombre' => '	OSPINA	', 'codigo_dian' => 52506, 'departamento_id' => 17],
            ['nombre' => '	PIZARRO	', 'codigo_dian' => 52520, 'departamento_id' => 17],
            ['nombre' => '	POLICARPA	', 'codigo_dian' => 52540, 'departamento_id' => 17],
            ['nombre' => '	POTOSI	', 'codigo_dian' => 52560, 'departamento_id' => 17],
            ['nombre' => '	PROVIDENCIA	', 'codigo_dian' => 52565, 'departamento_id' => 17],
            ['nombre' => '	PUERRES	', 'codigo_dian' => 52573, 'departamento_id' => 17],
            ['nombre' => '	PUPIALES	', 'codigo_dian' => 52585, 'departamento_id' => 17],
            ['nombre' => '	RICAURTE	', 'codigo_dian' => 52612, 'departamento_id' => 17],
            ['nombre' => '	ROBERTO PAYAN	', 'codigo_dian' => 52621, 'departamento_id' => 17],
            ['nombre' => '	SAMANIEGO	', 'codigo_dian' => 52678, 'departamento_id' => 17],
            ['nombre' => '	SANDONA	', 'codigo_dian' => 52683, 'departamento_id' => 17],
            ['nombre' => '	SAN BERNARDO	', 'codigo_dian' => 52685, 'departamento_id' => 17],
            ['nombre' => '	SAN LORENZO	', 'codigo_dian' => 52687, 'departamento_id' => 17],
            ['nombre' => '	SAN PABLO	', 'codigo_dian' => 52693, 'departamento_id' => 17],
            ['nombre' => '	SAN PEDRO DE CARTAGO	', 'codigo_dian' => 52694, 'departamento_id' => 17],
            ['nombre' => '	SANTA BARBARA	', 'codigo_dian' => 52696, 'departamento_id' => 17],
            ['nombre' => '	SANTACRUZ	', 'codigo_dian' => 52699, 'departamento_id' => 17],
            ['nombre' => '	SAPUYES	', 'codigo_dian' => 52720, 'departamento_id' => 17],
            ['nombre' => '	TAMINANGO	', 'codigo_dian' => 52786, 'departamento_id' => 17],
            ['nombre' => '	TANGUA	', 'codigo_dian' => 52788, 'departamento_id' => 17],
            ['nombre' => '	TUMACO	', 'codigo_dian' => 52835, 'departamento_id' => 17],
            ['nombre' => '	TUQUERRES	', 'codigo_dian' => 52838, 'departamento_id' => 17],
            ['nombre' => '	YACUANQUER	', 'codigo_dian' => 52885, 'departamento_id' => 17],
            ['nombre' => '	CUCUTA	', 'codigo_dian' => 54001, 'departamento_id' => 18],
            ['nombre' => '	ABREGO	', 'codigo_dian' => 54003, 'departamento_id' => 18],
            ['nombre' => '	ARBOLEDAS	', 'codigo_dian' => 54051, 'departamento_id' => 18],
            ['nombre' => '	BOCHALEMA	', 'codigo_dian' => 54099, 'departamento_id' => 18],
            ['nombre' => '	BUCARASICA	', 'codigo_dian' => 54109, 'departamento_id' => 18],
            ['nombre' => '	CACOTA	', 'codigo_dian' => 54125, 'departamento_id' => 18],
            ['nombre' => '	CACHIRA	', 'codigo_dian' => 54128, 'departamento_id' => 18],
            ['nombre' => '	CHINACOTA	', 'codigo_dian' => 54172, 'departamento_id' => 18],
            ['nombre' => '	CHITAGA	', 'codigo_dian' => 54174, 'departamento_id' => 18],
            ['nombre' => '	CONVENCION	', 'codigo_dian' => 54206, 'departamento_id' => 18],
            ['nombre' => '	CUCUTILLA	', 'codigo_dian' => 54223, 'departamento_id' => 18],
            ['nombre' => '	DURANIA	', 'codigo_dian' => 54239, 'departamento_id' => 18],
            ['nombre' => '	EL CARMEN	', 'codigo_dian' => 54245, 'departamento_id' => 18],
            ['nombre' => '	EL TARRA	', 'codigo_dian' => 54250, 'departamento_id' => 18],
            ['nombre' => '	EL ZULIA	', 'codigo_dian' => 54261, 'departamento_id' => 18],
            ['nombre' => '	GRAMALOTE	', 'codigo_dian' => 54313, 'departamento_id' => 18],
            ['nombre' => '	HACARI	', 'codigo_dian' => 54344, 'departamento_id' => 18],
            ['nombre' => '	HERRAN	', 'codigo_dian' => 54347, 'departamento_id' => 18],
            ['nombre' => '	LABATECA	', 'codigo_dian' => 54377, 'departamento_id' => 18],
            ['nombre' => '	LA ESPERANZA	', 'codigo_dian' => 54385, 'departamento_id' => 18],
            ['nombre' => '	LA PLAYA	', 'codigo_dian' => 54398, 'departamento_id' => 18],
            ['nombre' => '	LOS PATIOS	', 'codigo_dian' => 54405, 'departamento_id' => 18],
            ['nombre' => '	LOURDES	', 'codigo_dian' => 54418, 'departamento_id' => 18],
            ['nombre' => '	MUTISCUA	', 'codigo_dian' => 54480, 'departamento_id' => 18],
            ['nombre' => '	OCAÑA	', 'codigo_dian' => 54498, 'departamento_id' => 18],
            ['nombre' => '	PAMPLONA	', 'codigo_dian' => 54518, 'departamento_id' => 18],
            ['nombre' => '	PAMPLONITA	', 'codigo_dian' => 54520, 'departamento_id' => 18],
            ['nombre' => '	PUERTO SANTANDER	', 'codigo_dian' => 54553, 'departamento_id' => 18],
            ['nombre' => '	RAGONVALIA	', 'codigo_dian' => 54599, 'departamento_id' => 18],
            ['nombre' => '	SALAZAR	', 'codigo_dian' => 54660, 'departamento_id' => 18],
            ['nombre' => '	SAN CALIXTO	', 'codigo_dian' => 54670, 'departamento_id' => 18],
            ['nombre' => '	SAN CAYETANO	', 'codigo_dian' => 54673, 'departamento_id' => 18],
            ['nombre' => '	SANTIAGO	', 'codigo_dian' => 54680, 'departamento_id' => 18],
            ['nombre' => '	SARDINATA	', 'codigo_dian' => 54720, 'departamento_id' => 18],
            ['nombre' => '	SILOS	', 'codigo_dian' => 54743, 'departamento_id' => 18],
            ['nombre' => '	TEORAMA	', 'codigo_dian' => 54800, 'departamento_id' => 18],
            ['nombre' => '	TIBU	', 'codigo_dian' => 54810, 'departamento_id' => 18],
            ['nombre' => '	TOLEDO	', 'codigo_dian' => 54820, 'departamento_id' => 18],
            ['nombre' => '	VILLACARO	', 'codigo_dian' => 54871, 'departamento_id' => 18],
            ['nombre' => '	VILLA DEL ROSARIO	', 'codigo_dian' => 54874, 'departamento_id' => 18],
            ['nombre' => '	ARMENIA	', 'codigo_dian' => 63001, 'departamento_id' => 19],
            ['nombre' => '	BUENAVISTA	', 'codigo_dian' => 63111, 'departamento_id' => 19],
            ['nombre' => '	CALARCA	', 'codigo_dian' => 63130, 'departamento_id' => 19],
            ['nombre' => '	CIRCASIA	', 'codigo_dian' => 63190, 'departamento_id' => 19],
            ['nombre' => '	CORDOBA	', 'codigo_dian' => 63212, 'departamento_id' => 19],
            ['nombre' => '	FILANDIA	', 'codigo_dian' => 63272, 'departamento_id' => 19],
            ['nombre' => '	GENOVA	', 'codigo_dian' => 63302, 'departamento_id' => 19],
            ['nombre' => '	LA TEBAIDA	', 'codigo_dian' => 63401, 'departamento_id' => 19],
            ['nombre' => '	MONTENEGRO	', 'codigo_dian' => 63470, 'departamento_id' => 19],
            ['nombre' => '	PIJAO	', 'codigo_dian' => 63548, 'departamento_id' => 19],
            ['nombre' => '	QUIMBAYA	', 'codigo_dian' => 63594, 'departamento_id' => 19],
            ['nombre' => '	SALENTO	', 'codigo_dian' => 63690, 'departamento_id' => 19],
            ['nombre' => '	PEREIRA	', 'codigo_dian' => 66001, 'departamento_id' => 20],
            ['nombre' => '	APIA	', 'codigo_dian' => 66045, 'departamento_id' => 20],
            ['nombre' => '	BALBOA	', 'codigo_dian' => 66075, 'departamento_id' => 20],
            ['nombre' => '	BELEN DE UMBRIA	', 'codigo_dian' => 66088, 'departamento_id' => 20],
            ['nombre' => '	DOS QUEBRADAS	', 'codigo_dian' => 66170, 'departamento_id' => 20],
            ['nombre' => '	GUATICA	', 'codigo_dian' => 66318, 'departamento_id' => 20],
            ['nombre' => '	LA CELIA	', 'codigo_dian' => 66383, 'departamento_id' => 20],
            ['nombre' => '	LA VIRGINIA	', 'codigo_dian' => 66400, 'departamento_id' => 20],
            ['nombre' => '	MARSELLA	', 'codigo_dian' => 66440, 'departamento_id' => 20],
            ['nombre' => '	MISTRATO	', 'codigo_dian' => 66456, 'departamento_id' => 20],
            ['nombre' => '	PUEBLO RICO	', 'codigo_dian' => 66572, 'departamento_id' => 20],
            ['nombre' => '	QUINCHIA	', 'codigo_dian' => 66594, 'departamento_id' => 20],
            ['nombre' => '	SANTA ROSA DE CABAL	', 'codigo_dian' => 66682, 'departamento_id' => 20],
            ['nombre' => '	SANTUARIO	', 'codigo_dian' => 66687, 'departamento_id' => 20],
            ['nombre' => '	BUCARAMANGA	', 'codigo_dian' => 68001, 'departamento_id' => 21],
            ['nombre' => '	AGUADA	', 'codigo_dian' => 68013, 'departamento_id' => 21],
            ['nombre' => '	ALBANIA	', 'codigo_dian' => 68020, 'departamento_id' => 21],
            ['nombre' => '	ARATOCA	', 'codigo_dian' => 68051, 'departamento_id' => 21],
            ['nombre' => '	BARBOSA	', 'codigo_dian' => 68077, 'departamento_id' => 21],
            ['nombre' => '	BARICHARA	', 'codigo_dian' => 68079, 'departamento_id' => 21],
            ['nombre' => '	BARRANCABERMEJA	', 'codigo_dian' => 68081, 'departamento_id' => 21],
            ['nombre' => '	BETULIA	', 'codigo_dian' => 68092, 'departamento_id' => 21],
            ['nombre' => '	BOLIVAR	', 'codigo_dian' => 68101, 'departamento_id' => 21],
            ['nombre' => '	CABRERA	', 'codigo_dian' => 68121, 'departamento_id' => 21],
            ['nombre' => '	CALIFORNIA	', 'codigo_dian' => 68132, 'departamento_id' => 21],
            ['nombre' => '	CAPITANEJO	', 'codigo_dian' => 68147, 'departamento_id' => 21],
            ['nombre' => '	CARCASI	', 'codigo_dian' => 68152, 'departamento_id' => 21],
            ['nombre' => '	CEPITA	', 'codigo_dian' => 68160, 'departamento_id' => 21],
            ['nombre' => '	CERRITO	', 'codigo_dian' => 68162, 'departamento_id' => 21],
            ['nombre' => '	CHARALA	', 'codigo_dian' => 68167, 'departamento_id' => 21],
            ['nombre' => '	CHARTA	', 'codigo_dian' => 68169, 'departamento_id' => 21],
            ['nombre' => '	CHIMA	', 'codigo_dian' => 68176, 'departamento_id' => 21],
            ['nombre' => '	CHIPATA	', 'codigo_dian' => 68179, 'departamento_id' => 21],
            ['nombre' => '	CIMITARRA	', 'codigo_dian' => 68190, 'departamento_id' => 21],
            ['nombre' => '	CONCEPCION	', 'codigo_dian' => 68207, 'departamento_id' => 21],
            ['nombre' => '	CONFINES	', 'codigo_dian' => 68209, 'departamento_id' => 21],
            ['nombre' => '	CONTRATACION	', 'codigo_dian' => 68211, 'departamento_id' => 21],
            ['nombre' => '	COROMORO	', 'codigo_dian' => 68217, 'departamento_id' => 21],
            ['nombre' => '	CURITI	', 'codigo_dian' => 68229, 'departamento_id' => 21],
            ['nombre' => '	EL CARMEN	', 'codigo_dian' => 68235, 'departamento_id' => 21],
            ['nombre' => '	EL GUACAMAYO	', 'codigo_dian' => 68245, 'departamento_id' => 21],
            ['nombre' => '	EL PEÑON	', 'codigo_dian' => 68250, 'departamento_id' => 21],
            ['nombre' => '	EL PLAYON	', 'codigo_dian' => 68255, 'departamento_id' => 21],
            ['nombre' => '	ENCINO	', 'codigo_dian' => 68264, 'departamento_id' => 21],
            ['nombre' => '	ENCISO	', 'codigo_dian' => 68266, 'departamento_id' => 21],
            ['nombre' => '	FLORIAN	', 'codigo_dian' => 68271, 'departamento_id' => 21],
            ['nombre' => '	FLORIDABLANCA	', 'codigo_dian' => 68276, 'departamento_id' => 21],
            ['nombre' => '	GALAN	', 'codigo_dian' => 68296, 'departamento_id' => 21],
            ['nombre' => '	GAMBITA	', 'codigo_dian' => 68298, 'departamento_id' => 21],
            ['nombre' => '	GIRON	', 'codigo_dian' => 68307, 'departamento_id' => 21],
            ['nombre' => '	GUACA	', 'codigo_dian' => 68318, 'departamento_id' => 21],
            ['nombre' => '	GUADALUPE	', 'codigo_dian' => 68320, 'departamento_id' => 21],
            ['nombre' => '	GUAPOTA	', 'codigo_dian' => 68322, 'departamento_id' => 21],
            ['nombre' => '	GUAVATA	', 'codigo_dian' => 68324, 'departamento_id' => 21],
            ['nombre' => '	GUEPSA	', 'codigo_dian' => 68327, 'departamento_id' => 21],
            ['nombre' => '	HATO	', 'codigo_dian' => 68344, 'departamento_id' => 21],
            ['nombre' => '	JESUS MARIA	', 'codigo_dian' => 68368, 'departamento_id' => 21],
            ['nombre' => '	JORDAN	', 'codigo_dian' => 68370, 'departamento_id' => 21],
            ['nombre' => '	LA BELLEZA	', 'codigo_dian' => 68377, 'departamento_id' => 21],
            ['nombre' => '	LANDAZURI	', 'codigo_dian' => 68385, 'departamento_id' => 21],
            ['nombre' => '	LA PAZ	', 'codigo_dian' => 68397, 'departamento_id' => 21],
            ['nombre' => '	LEBRIJA	', 'codigo_dian' => 68406, 'departamento_id' => 21],
            ['nombre' => '	LOS SANTOS	', 'codigo_dian' => 68418, 'departamento_id' => 21],
            ['nombre' => '	MACARAVITA	', 'codigo_dian' => 68425, 'departamento_id' => 21],
            ['nombre' => '	MALAGA	', 'codigo_dian' => 68432, 'departamento_id' => 21],
            ['nombre' => '	MATANZA	', 'codigo_dian' => 68444, 'departamento_id' => 21],
            ['nombre' => '	MOGOTES	', 'codigo_dian' => 68464, 'departamento_id' => 21],
            ['nombre' => '	MOLAGAVITA	', 'codigo_dian' => 68468, 'departamento_id' => 21],
            ['nombre' => '	OCAMONTE	', 'codigo_dian' => 68498, 'departamento_id' => 21],
            ['nombre' => '	OIBA	', 'codigo_dian' => 68500, 'departamento_id' => 21],
            ['nombre' => '	ONZAGA	', 'codigo_dian' => 68502, 'departamento_id' => 21],
            ['nombre' => '	PALMAR	', 'codigo_dian' => 68522, 'departamento_id' => 21],
            ['nombre' => '	PALMAS DEL SOCORRO	', 'codigo_dian' => 68524, 'departamento_id' => 21],
            ['nombre' => '	PARAMO	', 'codigo_dian' => 68533, 'departamento_id' => 21],
            ['nombre' => '	PIEDECUESTA	', 'codigo_dian' => 68547, 'departamento_id' => 21],
            ['nombre' => '	PINCHOTE	', 'codigo_dian' => 68549, 'departamento_id' => 21],
            ['nombre' => '	PUENTE NACIONAL	', 'codigo_dian' => 68572, 'departamento_id' => 21],
            ['nombre' => '	PUERTO PARRA	', 'codigo_dian' => 68573, 'departamento_id' => 21],
            ['nombre' => '	PUERTO WILCHES	', 'codigo_dian' => 68575, 'departamento_id' => 21],
            ['nombre' => '	RIONEGRO	', 'codigo_dian' => 68615, 'departamento_id' => 21],
            ['nombre' => '	SABANA DE TORRES	', 'codigo_dian' => 68655, 'departamento_id' => 21],
            ['nombre' => '	SAN ANDRES	', 'codigo_dian' => 68669, 'departamento_id' => 21],
            ['nombre' => '	SAN BENITO	', 'codigo_dian' => 68673, 'departamento_id' => 21],
            ['nombre' => '	SAN GIL	', 'codigo_dian' => 68679, 'departamento_id' => 21],
            ['nombre' => '	SAN JOAQUIN	', 'codigo_dian' => 68682, 'departamento_id' => 21],
            ['nombre' => '	SAN JOSE DE MIRANDA	', 'codigo_dian' => 68684, 'departamento_id' => 21],
            ['nombre' => '	SAN MIGUEL	', 'codigo_dian' => 68686, 'departamento_id' => 21],
            ['nombre' => '	SAN VICENTE DE CHUCURI	', 'codigo_dian' => 68689, 'departamento_id' => 21],
            ['nombre' => '	SANTA BARBARA	', 'codigo_dian' => 68705, 'departamento_id' => 21],
            ['nombre' => '	SANTA HELENA	', 'codigo_dian' => 68720, 'departamento_id' => 21],
            ['nombre' => '	SIMACOTA	', 'codigo_dian' => 68745, 'departamento_id' => 21],
            ['nombre' => '	SOCORRO	', 'codigo_dian' => 68755, 'departamento_id' => 21],
            ['nombre' => '	SUAITA	', 'codigo_dian' => 68770, 'departamento_id' => 21],
            ['nombre' => '	SUCRE	', 'codigo_dian' => 68773, 'departamento_id' => 21],
            ['nombre' => '	SURATA	', 'codigo_dian' => 68780, 'departamento_id' => 21],
            ['nombre' => '	TONA	', 'codigo_dian' => 68820, 'departamento_id' => 21],
            ['nombre' => '	VALLE SAN JOSE	', 'codigo_dian' => 68855, 'departamento_id' => 21],
            ['nombre' => '	VELEZ	', 'codigo_dian' => 68861, 'departamento_id' => 21],
            ['nombre' => '	VETAS	', 'codigo_dian' => 68867, 'departamento_id' => 21],
            ['nombre' => '	VILLANUEVA	', 'codigo_dian' => 68872, 'departamento_id' => 21],
            ['nombre' => '	ZAPATOCA	', 'codigo_dian' => 68895, 'departamento_id' => 21],
            ['nombre' => '	SINCELEJO	', 'codigo_dian' => 70001, 'departamento_id' => 22],
            ['nombre' => '	BUENAVISTA	', 'codigo_dian' => 70110, 'departamento_id' => 22],
            ['nombre' => '	CAIMITO	', 'codigo_dian' => 70124, 'departamento_id' => 22],
            ['nombre' => '	COLOSO	', 'codigo_dian' => 70204, 'departamento_id' => 22],
            ['nombre' => '	COROZAL	', 'codigo_dian' => 70215, 'departamento_id' => 22],
            ['nombre' => '	COVEÑAS	', 'codigo_dian' => 70221, 'departamento_id' => 22],
            ['nombre' => '	CHALAN	', 'codigo_dian' => 70230, 'departamento_id' => 22],
            ['nombre' => '	EL ROBLE	', 'codigo_dian' => 70233, 'departamento_id' => 22],
            ['nombre' => '	GALERAS	', 'codigo_dian' => 70235, 'departamento_id' => 22],
            ['nombre' => '	GUARANDA	', 'codigo_dian' => 70265, 'departamento_id' => 22],
            ['nombre' => '	LA UNION	', 'codigo_dian' => 70400, 'departamento_id' => 22],
            ['nombre' => '	LOS PALMITOS	', 'codigo_dian' => 70418, 'departamento_id' => 22],
            ['nombre' => '	MAJAGUAL	', 'codigo_dian' => 70429, 'departamento_id' => 22],
            ['nombre' => '	MORROA	', 'codigo_dian' => 70473, 'departamento_id' => 22],
            ['nombre' => '	OVEJAS	', 'codigo_dian' => 70508, 'departamento_id' => 22],
            ['nombre' => '	PALMITO	', 'codigo_dian' => 70523, 'departamento_id' => 22],
            ['nombre' => '	SAMPUES	', 'codigo_dian' => 70670, 'departamento_id' => 22],
            ['nombre' => '	SAN BENITO ABAD	', 'codigo_dian' => 70678, 'departamento_id' => 22],
            ['nombre' => '	SAN JUAN DE BETULIA	', 'codigo_dian' => 70702, 'departamento_id' => 22],
            ['nombre' => '	SAN MARCOS	', 'codigo_dian' => 70708, 'departamento_id' => 22],
            ['nombre' => '	SAN ONOFRE	', 'codigo_dian' => 70713, 'departamento_id' => 22],
            ['nombre' => '	SAN PEDRO	', 'codigo_dian' => 70717, 'departamento_id' => 22],
            ['nombre' => '	SINCE	', 'codigo_dian' => 70742, 'departamento_id' => 22],
            ['nombre' => '	SUCRE	', 'codigo_dian' => 70771, 'departamento_id' => 22],
            ['nombre' => '	TOLU	', 'codigo_dian' => 70820, 'departamento_id' => 22],
            ['nombre' => '	TOLUVIEJO	', 'codigo_dian' => 70823, 'departamento_id' => 22],
            ['nombre' => '	IBAGUE	', 'codigo_dian' => 73001, 'departamento_id' => 23],
            ['nombre' => '	ALPUJARRA	', 'codigo_dian' => 73024, 'departamento_id' => 23],
            ['nombre' => '	ALVARADO	', 'codigo_dian' => 73026, 'departamento_id' => 23],
            ['nombre' => '	AMBALEMA	', 'codigo_dian' => 73030, 'departamento_id' => 23],
            ['nombre' => '	ANZOATEGUI	', 'codigo_dian' => 73043, 'departamento_id' => 23],
            ['nombre' => '	ARMERO (GUAYABAL)	', 'codigo_dian' => 73055, 'departamento_id' => 23],
            ['nombre' => '	ATACO	', 'codigo_dian' => 73067, 'departamento_id' => 23],
            ['nombre' => '	CAJAMARCA	', 'codigo_dian' => 73124, 'departamento_id' => 23],
            ['nombre' => '	CARMEN APICALA	', 'codigo_dian' => 73148, 'departamento_id' => 23],
            ['nombre' => '	CASABIANCA	', 'codigo_dian' => 73152, 'departamento_id' => 23],
            ['nombre' => '	CHAPARRAL	', 'codigo_dian' => 73168, 'departamento_id' => 23],
            ['nombre' => '	COELLO	', 'codigo_dian' => 73200, 'departamento_id' => 23],
            ['nombre' => '	COYAIMA	', 'codigo_dian' => 73217, 'departamento_id' => 23],
            ['nombre' => '	CUNDAY	', 'codigo_dian' => 73226, 'departamento_id' => 23],
            ['nombre' => '	DOLORES	', 'codigo_dian' => 73236, 'departamento_id' => 23],
            ['nombre' => '	ESPINAL	', 'codigo_dian' => 73268, 'departamento_id' => 23],
            ['nombre' => '	FALAN	', 'codigo_dian' => 73270, 'departamento_id' => 23],
            ['nombre' => '	FLANDES	', 'codigo_dian' => 73275, 'departamento_id' => 23],
            ['nombre' => '	FRESNO	', 'codigo_dian' => 73283, 'departamento_id' => 23],
            ['nombre' => '	GUAMO	', 'codigo_dian' => 73319, 'departamento_id' => 23],
            ['nombre' => '	HERVEO	', 'codigo_dian' => 73347, 'departamento_id' => 23],
            ['nombre' => '	HONDA	', 'codigo_dian' => 73349, 'departamento_id' => 23],
            ['nombre' => '	ICONONZO	', 'codigo_dian' => 73352, 'departamento_id' => 23],
            ['nombre' => '	LERIDA	', 'codigo_dian' => 73408, 'departamento_id' => 23],
            ['nombre' => '	LIBANO	', 'codigo_dian' => 73411, 'departamento_id' => 23],
            ['nombre' => '	MARIQUITA	', 'codigo_dian' => 73443, 'departamento_id' => 23],
            ['nombre' => '	MELGAR	', 'codigo_dian' => 73449, 'departamento_id' => 23],
            ['nombre' => '	MURILLO	', 'codigo_dian' => 73461, 'departamento_id' => 23],
            ['nombre' => '	NATAGAIMA	', 'codigo_dian' => 73483, 'departamento_id' => 23],
            ['nombre' => '	ORTEGA	', 'codigo_dian' => 73504, 'departamento_id' => 23],
            ['nombre' => '	PALOCABILDO	', 'codigo_dian' => 73520, 'departamento_id' => 23],
            ['nombre' => '	PIEDRAS	', 'codigo_dian' => 73547, 'departamento_id' => 23],
            ['nombre' => '	PLANADAS	', 'codigo_dian' => 73555, 'departamento_id' => 23],
            ['nombre' => '	PRADO	', 'codigo_dian' => 73563, 'departamento_id' => 23],
            ['nombre' => '	PURIFICACION	', 'codigo_dian' => 73585, 'departamento_id' => 23],
            ['nombre' => '	RIOBLANCO	', 'codigo_dian' => 73616, 'departamento_id' => 23],
            ['nombre' => '	RONCESVALLES	', 'codigo_dian' => 73622, 'departamento_id' => 23],
            ['nombre' => '	ROVIRA	', 'codigo_dian' => 73624, 'departamento_id' => 23],
            ['nombre' => '	SALDAÑA	', 'codigo_dian' => 73671, 'departamento_id' => 23],
            ['nombre' => '	SAN ANTONIO	', 'codigo_dian' => 73675, 'departamento_id' => 23],
            ['nombre' => '	SAN LUIS	', 'codigo_dian' => 73678, 'departamento_id' => 23],
            ['nombre' => '	SANTA ISABEL	', 'codigo_dian' => 73686, 'departamento_id' => 23],
            ['nombre' => '	SUAREZ	', 'codigo_dian' => 73770, 'departamento_id' => 23],
            ['nombre' => '	VALLE DE S JUAN	', 'codigo_dian' => 73854, 'departamento_id' => 23],
            ['nombre' => '	VENADILLO	', 'codigo_dian' => 73861, 'departamento_id' => 23],
            ['nombre' => '	VILLAHERMOSA	', 'codigo_dian' => 73870, 'departamento_id' => 23],
            ['nombre' => '	VILLARRICA	', 'codigo_dian' => 73873, 'departamento_id' => 23],
            ['nombre' => '	CALI	', 'codigo_dian' => 76001, 'departamento_id' => 24],
            ['nombre' => '	ALCALA	', 'codigo_dian' => 76020, 'departamento_id' => 24],
            ['nombre' => '	ANDALUCIA	', 'codigo_dian' => 76036, 'departamento_id' => 24],
            ['nombre' => '	ANSERMANUEVO	', 'codigo_dian' => 76041, 'departamento_id' => 24],
            ['nombre' => '	ARGELIA	', 'codigo_dian' => 76054, 'departamento_id' => 24],
            ['nombre' => '	BOLIVAR	', 'codigo_dian' => 76100, 'departamento_id' => 24],
            ['nombre' => '	BUENAVENTURA	', 'codigo_dian' => 76109, 'departamento_id' => 24],
            ['nombre' => '	BUGA	', 'codigo_dian' => 76111, 'departamento_id' => 24],
            ['nombre' => '	BUGALAGRANDE	', 'codigo_dian' => 76113, 'departamento_id' => 24],
            ['nombre' => '	CAICEDONIA	', 'codigo_dian' => 76122, 'departamento_id' => 24],
            ['nombre' => '	CALIMA	', 'codigo_dian' => 76126, 'departamento_id' => 24],
            ['nombre' => '	CANDELARIA	', 'codigo_dian' => 76130, 'departamento_id' => 24],
            ['nombre' => '	CARTAGO	', 'codigo_dian' => 76147, 'departamento_id' => 24],
            ['nombre' => '	DAGUA	', 'codigo_dian' => 76233, 'departamento_id' => 24],
            ['nombre' => '	EL AGUILA	', 'codigo_dian' => 76243, 'departamento_id' => 24],
            ['nombre' => '	EL CAIRO	', 'codigo_dian' => 76246, 'departamento_id' => 24],
            ['nombre' => '	EL CERRITO	', 'codigo_dian' => 76248, 'departamento_id' => 24],
            ['nombre' => '	EL DOVIO	', 'codigo_dian' => 76250, 'departamento_id' => 24],
            ['nombre' => '	FLORIDA	', 'codigo_dian' => 76275, 'departamento_id' => 24],
            ['nombre' => '	GINEBRA	', 'codigo_dian' => 76306, 'departamento_id' => 24],
            ['nombre' => '	GUACARI	', 'codigo_dian' => 76318, 'departamento_id' => 24],
            ['nombre' => '	JAMUNDI	', 'codigo_dian' => 76364, 'departamento_id' => 24],
            ['nombre' => '	LA CUMBRE	', 'codigo_dian' => 76377, 'departamento_id' => 24],
            ['nombre' => '	LA UNION	', 'codigo_dian' => 76400, 'departamento_id' => 24],
            ['nombre' => '	LA VICTORIA	', 'codigo_dian' => 76403, 'departamento_id' => 24],
            ['nombre' => '	OBANDO	', 'codigo_dian' => 76497, 'departamento_id' => 24],
            ['nombre' => '	PALMIRA	', 'codigo_dian' => 76520, 'departamento_id' => 24],
            ['nombre' => '	PRADERA	', 'codigo_dian' => 76563, 'departamento_id' => 24],
            ['nombre' => '	RESTREPO	', 'codigo_dian' => 76606, 'departamento_id' => 24],
            ['nombre' => '	RIOFRIO	', 'codigo_dian' => 76616, 'departamento_id' => 24],
            ['nombre' => '	ROLDANILLO	', 'codigo_dian' => 76622, 'departamento_id' => 24],
            ['nombre' => '	SAN PEDRO	', 'codigo_dian' => 76670, 'departamento_id' => 24],
            ['nombre' => '	SEVILLA	', 'codigo_dian' => 76736, 'departamento_id' => 24],
            ['nombre' => '	TORO	', 'codigo_dian' => 76823, 'departamento_id' => 24],
            ['nombre' => '	TRUJILLO	', 'codigo_dian' => 76828, 'departamento_id' => 24],
            ['nombre' => '	TULUA	', 'codigo_dian' => 76834, 'departamento_id' => 24],
            ['nombre' => '	ULLOA	', 'codigo_dian' => 76845, 'departamento_id' => 24],
            ['nombre' => '	VERSALLES	', 'codigo_dian' => 76863, 'departamento_id' => 24],
            ['nombre' => '	VIJES	', 'codigo_dian' => 76869, 'departamento_id' => 24],
            ['nombre' => '	YOTOCO	', 'codigo_dian' => 76890, 'departamento_id' => 24],
            ['nombre' => '	YUMBO	', 'codigo_dian' => 76892, 'departamento_id' => 24],
            ['nombre' => '	ZARZAL	', 'codigo_dian' => 76895, 'departamento_id' => 24],
            ['nombre' => '	ARAUCA	', 'codigo_dian' => 81001, 'departamento_id' => 25],
            ['nombre' => '	ARAUQUITA	', 'codigo_dian' => 81065, 'departamento_id' => 25],
            ['nombre' => '	CRAVO NORTE	', 'codigo_dian' => 81220, 'departamento_id' => 25],
            ['nombre' => '	FORTUL	', 'codigo_dian' => 81300, 'departamento_id' => 25],
            ['nombre' => '	PUERTO RONDON	', 'codigo_dian' => 81591, 'departamento_id' => 25],
            ['nombre' => '	SARAVENA	', 'codigo_dian' => 81736, 'departamento_id' => 25],
            ['nombre' => '	TAME	', 'codigo_dian' => 81794, 'departamento_id' => 25],
            ['nombre' => '	YOPAL	', 'codigo_dian' => 85001, 'departamento_id' => 26],
            ['nombre' => '	AGUAZUL	', 'codigo_dian' => 85010, 'departamento_id' => 26],
            ['nombre' => '	CHAMEZA	', 'codigo_dian' => 85015, 'departamento_id' => 26],
            ['nombre' => '	HATO COROZAL	', 'codigo_dian' => 85125, 'departamento_id' => 26],
            ['nombre' => '	LA SALINA	', 'codigo_dian' => 85136, 'departamento_id' => 26],
            ['nombre' => '	MANI	', 'codigo_dian' => 85139, 'departamento_id' => 26],
            ['nombre' => '	MONTERREY	', 'codigo_dian' => 85162, 'departamento_id' => 26],
            ['nombre' => '	NUNCHIA	', 'codigo_dian' => 85225, 'departamento_id' => 26],
            ['nombre' => '	OROCUE	', 'codigo_dian' => 85230, 'departamento_id' => 26],
            ['nombre' => '	PAZ DE ARIPORO	', 'codigo_dian' => 85250, 'departamento_id' => 26],
            ['nombre' => '	PORE	', 'codigo_dian' => 85263, 'departamento_id' => 26],
            ['nombre' => '	RECETOR	', 'codigo_dian' => 85279, 'departamento_id' => 26],
            ['nombre' => '	SABANALARGA	', 'codigo_dian' => 85300, 'departamento_id' => 26],
            ['nombre' => '	SACAMA	', 'codigo_dian' => 85315, 'departamento_id' => 26],
            ['nombre' => '	SAN LUIS DE PALENQUE	', 'codigo_dian' => 85325, 'departamento_id' => 26],
            ['nombre' => '	TAMARA	', 'codigo_dian' => 85400, 'departamento_id' => 26],
            ['nombre' => '	TAURAMENA	', 'codigo_dian' => 85410, 'departamento_id' => 26],
            ['nombre' => '	TRINIDAD	', 'codigo_dian' => 85430, 'departamento_id' => 26],
            ['nombre' => '	VILLANUEVA	', 'codigo_dian' => 85440, 'departamento_id' => 26],
            ['nombre' => '	MOCOA	', 'codigo_dian' => 86001, 'departamento_id' => 27],
            ['nombre' => '	COLON	', 'codigo_dian' => 86219, 'departamento_id' => 27],
            ['nombre' => '	ORITO	', 'codigo_dian' => 86320, 'departamento_id' => 27],
            ['nombre' => '	PUERTO ASIS	', 'codigo_dian' => 86568, 'departamento_id' => 27],
            ['nombre' => '	PUERTO CAYCEDO	', 'codigo_dian' => 86569, 'departamento_id' => 27],
            ['nombre' => '	PUERTO GUZMAN	', 'codigo_dian' => 86571, 'departamento_id' => 27],
            ['nombre' => '	PUERTO LEGUIZAMO	', 'codigo_dian' => 86573, 'departamento_id' => 27],
            ['nombre' => '	SIBUNDOY	', 'codigo_dian' => 86749, 'departamento_id' => 27],
            ['nombre' => '	SAN FRANCISCO	', 'codigo_dian' => 86755, 'departamento_id' => 27],
            ['nombre' => '	SAN MIGUEL	', 'codigo_dian' => 86757, 'departamento_id' => 27],
            ['nombre' => '	SANTIAGO	', 'codigo_dian' => 86760, 'departamento_id' => 27],
            ['nombre' => '	VALLE DEL GUAMUEZ	', 'codigo_dian' => 86865, 'departamento_id' => 27],
            ['nombre' => '	VILLAGARZON	', 'codigo_dian' => 86885, 'departamento_id' => 27],
            ['nombre' => '	SAN ANDRES	', 'codigo_dian' => 88001, 'departamento_id' => 28],
            ['nombre' => '	PROVIDENCIA	', 'codigo_dian' => 88564, 'departamento_id' => 28],
            ['nombre' => '	LETICIA	', 'codigo_dian' => 91001, 'departamento_id' => 29],
            ['nombre' => '	PUERTO NARIÑO	', 'codigo_dian' => 91540, 'departamento_id' => 29],
            ['nombre' => '	PUERTO INIRIDA	', 'codigo_dian' => 94001, 'departamento_id' => 30],
            ['nombre' => '	SAN JOSE DEL GUAVIARE	', 'codigo_dian' => 95001, 'departamento_id' => 31],
            ['nombre' => '	CALAMAR	', 'codigo_dian' => 95015, 'departamento_id' => 31],
            ['nombre' => '	EL RETORNO	', 'codigo_dian' => 95025, 'departamento_id' => 31],
            ['nombre' => '	MIRAFLORES	', 'codigo_dian' => 95200, 'departamento_id' => 31],
            ['nombre' => '	MITU	', 'codigo_dian' => 97001, 'departamento_id' => 32],
            ['nombre' => '	CARURU	', 'codigo_dian' => 97161, 'departamento_id' => 32],
            ['nombre' => '	TARAIRA	', 'codigo_dian' => 97666, 'departamento_id' => 32],
            ['nombre' => '	PUERTO CARREÑO	', 'codigo_dian' => 99001, 'departamento_id' => 33],
            ['nombre' => '	LA PRIMAVERA	', 'codigo_dian' => 99524, 'departamento_id' => 33],
            ['nombre' => '	SANTA ROSALIA	', 'codigo_dian' => 99624, 'departamento_id' => 33],
            ['nombre' => '	CUMARIBO	', 'codigo_dian' => 99773, 'departamento_id' => 33],

        ];

        DB::table('ciudades')->insert($ciudades);
    }
}
